Repository DDog-org/daengle-server, pull requests merged in 2024-11, with the labels that each got.

#3 [feat/meongle-1] Spring Security + OAuth2.0 + Swagger
  build.gradle
  settings.gradle
  src/main/java/ddog/mungleserver/MeongleServerApplication.java
  src/main/java/ddog/mungleserver/global/presentation/ResponseDto.java
  src/main/java/ddog/mungleserver/global/presentation/ResponseStatus.java
  src/main/java/ddog/mungleserver/infrastructure/auth/config/SecurityConfig.java
  src/main/java/ddog/mungleserver/infrastructure/auth/config/enums/Provider.java
  src/main/java/ddog/mungleserver/infrastructure/auth/config/enums/Role.java
  src/main/java/ddog/mungleserver/infrastructure/auth/config/jwt/JwtAccessDeniedHandler.java
  src/main/java/ddog/mungleserver/infrastructure/auth/config/jwt/JwtAuthenticationEntryPoint.java
  src/main/java/ddog/mungleserver/infrastructure/auth/config/jwt/JwtAuthenticationFilter.java
  src/main/java/ddog/mungleserver/infrastructure/auth/config/jwt/JwtTokenProvider.java
  src/main/java/ddog/mungleserver/infrastructure/auth/dto/KakaoAccessTokenDto.java
  src/main/java/ddog/mungleserver/infrastructure/auth/dto/RefreshTokenDto.java
  src/main/java/ddog/mungleserver/infrastructure/auth/dto/TokenAccountInfoDto.java
  src/main/java/ddog/mungleserver/infrastructure/auth/dto/TokenInfoDto.java
  src/main/java/ddog/mungleserver/infrastructure/auth/presentation/OAuthController.java
  src/main/java/ddog/mungleserver/infrastructure/auth/service/KakaoSocialService.java
  src/main/java/ddog/mungleserver/infrastructure/auth/service/OAuthService.java
  src/main/java/ddog/mungleserver/infrastructure/swagger/config/SwaggerConfig.java
  src/main/java/ddog/mungleserver/jpa/customer/Customer.java
  src/main/java/ddog/mungleserver/persistence/Customer/CustomerRepository.java
  src/test/java/ddog/mungleserver/MeongleServerApplicationTests.java
Labels: enhancement

#9 [feat/daengle-5] JWT 토큰 검증 및 Payload 정보 추출 단일화
  src/main/java/ddog/daengleserver/application/AccountService.java
  src/main/java/ddog/daengleserver/application/repository/AccountRepository.java
  src/main/java/ddog/daengleserver/domain/Account.java
  src/main/java/ddog/daengleserver/global/auth/application/OAuthService.java
  src/main/java/ddog/daengleserver/global/auth/config/SecurityConfig.java
  src/main/java/ddog/daengleserver/global/auth/config/WebConfig.java
  src/main/java/ddog/daengleserver/global/auth/config/jwt/JwtAuthenticationFilter.java
  src/main/java/ddog/daengleserver/global/auth/config/jwt/JwtTokenProvider.java
  src/main/java/ddog/daengleserver/global/auth/dto/PayloadDto.java
  src/main/java/ddog/daengleserver/global/auth/dto/TokenAccountInfoDto.java
  src/main/java/ddog/daengleserver/global/auth/dto/TokenInfoDto.java
  src/main/java/ddog/daengleserver/global/auth/presentation/OAuthController.java
  src/main/java/ddog/daengleserver/global/auth/resolver/PayloadArgumentResolver.java
  src/main/java/ddog/daengleserver/implementation/enums/AccountExceptionType.java
  src/main/java/ddog/daengleserver/infrastructure/AccountJpaRepository.java
  src/main/java/ddog/daengleserver/infrastructure/AccountRepositoryImpl.java
  src/main/java/ddog/daengleserver/infrastructure/jpa/AccountJpaEntity.java
  src/main/java/ddog/daengleserver/presentation/AccountController.java
  src/main/java/ddog/daengleserver/presentation/dto/request/UpdateNicknameDto.java
  src/main/java/ddog/daengleserver/presentation/dto/response/AccountInfoDto.java
  src/main/java/ddog/daengleserver/presentation/enums/AccountControllerResp.java
Labels: 💻 기능

#10 [release/daengle-4] WAS infra construction (release, api test)
  .gitignore
  Dockerfile
  compose.yml
  src/main/java/ddog/daengleserver/presentation/APITestController.java
Labels: release

#16 [feat/daengle-7] 사용자 미용 견적서 조회 및 등록 API 구현
  src/main/java/ddog/daengleserver/application/AccountService.java
  src/main/java/ddog/daengleserver/application/GroomingEstimateService.java
  src/main/java/ddog/daengleserver/application/repository/AccountRepository.java
  src/main/java/ddog/daengleserver/application/repository/GroomingEstimateRepository.java
  src/main/java/ddog/daengleserver/application/repository/UserRepository.java
  src/main/java/ddog/daengleserver/domain/Account.java
  src/main/java/ddog/daengleserver/domain/Pet.java
  src/main/java/ddog/daengleserver/domain/Provider.java
  src/main/java/ddog/daengleserver/domain/Role.java
  src/main/java/ddog/daengleserver/domain/User.java
  src/main/java/ddog/daengleserver/domain/estimate/EstimateStatus.java
  src/main/java/ddog/daengleserver/domain/estimate/GroomingEstimate.java
  src/main/java/ddog/daengleserver/domain/estimate/Proposal.java
  src/main/java/ddog/daengleserver/global/auth/application/OAuthService.java
  src/main/java/ddog/daengleserver/global/auth/config/enums/Provider.java
  src/main/java/ddog/daengleserver/global/auth/config/jwt/JwtAuthenticationFilter.java
  src/main/java/ddog/daengleserver/global/auth/config/jwt/JwtTokenProvider.java
  src/main/java/ddog/daengleserver/global/auth/dto/PayloadDto.java
  src/main/java/ddog/daengleserver/global/auth/dto/TokenAccountInfoDto.java
  src/main/java/ddog/daengleserver/global/auth/dto/TokenInfoDto.java
  src/main/java/ddog/daengleserver/global/auth/resolver/PayloadArgumentResolver.java
  src/main/java/ddog/daengleserver/infrastructure/AccountJpaRepository.java
  src/main/java/ddog/daengleserver/infrastructure/AccountRepositoryImpl.java
  src/main/java/ddog/daengleserver/infrastructure/GroomingEstimateEstimateRepositoryImpl.java
  src/main/java/ddog/daengleserver/infrastructure/GroomingEstimateJpaRepository.java
  src/main/java/ddog/daengleserver/infrastructure/UserJpaRepository.java
  src/main/java/ddog/daengleserver/infrastructure/UserRepositoryImpl.java
  src/main/java/ddog/daengleserver/infrastructure/jpa/AccountJpaEntity.java
  src/main/java/ddog/daengleserver/infrastructure/jpa/GroomingEstimateJpaEntity.java
  src/main/java/ddog/daengleserver/infrastructure/jpa/PetJpaEntity.java
  src/main/java/ddog/daengleserver/infrastructure/jpa/UserJpaEntity.java
  src/main/java/ddog/daengleserver/presentation/dto/request/DesignationGroomingEstimateReq.java
  src/main/java/ddog/daengleserver/presentation/dto/request/GeneralGroomingEstimateReq.java
  src/main/java/ddog/daengleserver/presentation/dto/response/AccountInfoDto.java
  src/main/java/ddog/daengleserver/presentation/dto/response/UserAddressAndPetsInfo.java
  src/main/java/ddog/daengleserver/presentation/enums/GroomingEstimateControllerResp.java
  src/main/java/ddog/daengleserver/presentation/user/GroomingEstimateController.java
Labels: 💻 기능

#20 [feat/daengle-9] 미용사 견적서 및 상세 내용 조회 및 요청 API
  src/main/java/ddog/daengleserver/application/GroomingEstimateService.java
  src/main/java/ddog/daengleserver/application/repository/GroomerRepository.java
  src/main/java/ddog/daengleserver/application/repository/GroomingEstimateRepository.java
  src/main/java/ddog/daengleserver/application/repository/UserRepository.java
  src/main/java/ddog/daengleserver/domain/Account.java
  src/main/java/ddog/daengleserver/domain/Groomer.java
  src/main/java/ddog/daengleserver/domain/Pet.java
  src/main/java/ddog/daengleserver/domain/User.java
  src/main/java/ddog/daengleserver/domain/Weight.java
  src/main/java/ddog/daengleserver/domain/estimate/EstimateStatus.java
  src/main/java/ddog/daengleserver/domain/estimate/GroomingEstimate.java
  src/main/java/ddog/daengleserver/global/auth/application/OAuthService.java
  src/main/java/ddog/daengleserver/global/auth/config/jwt/JwtAuthenticationFilter.java
  src/main/java/ddog/daengleserver/global/auth/dto/PayloadDto.java
  src/main/java/ddog/daengleserver/global/auth/dto/TokenAccountInfoDto.java
  src/main/java/ddog/daengleserver/global/auth/resolver/PayloadArgumentResolver.java
  src/main/java/ddog/daengleserver/infrastructure/AccountRepositoryImpl.java
  src/main/java/ddog/daengleserver/infrastructure/GroomerJpaRepository.java
  src/main/java/ddog/daengleserver/infrastructure/GroomerRepositoryImpl.java
  src/main/java/ddog/daengleserver/infrastructure/GroomingEstimateEstimateRepositoryImpl.java
  src/main/java/ddog/daengleserver/infrastructure/GroomingEstimateJpaRepository.java
  src/main/java/ddog/daengleserver/infrastructure/UserRepositoryImpl.java
  src/main/java/ddog/daengleserver/infrastructure/jpa/AccountJpaEntity.java
  src/main/java/ddog/daengleserver/infrastructure/jpa/GroomerJpaEntity.java
  src/main/java/ddog/daengleserver/infrastructure/jpa/GroomingEstimateJpaEntity.java
  src/main/java/ddog/daengleserver/infrastructure/jpa/PetJpaEntity.java
  src/main/java/ddog/daengleserver/infrastructure/jpa/UserJpaEntity.java
  src/main/java/ddog/daengleserver/presentation/estimate/GroomerEstimateController.java
  src/main/java/ddog/daengleserver/presentation/estimate/UserEstimateController.java
  src/main/java/ddog/daengleserver/presentation/estimate/dto/request/GroomerGroomingEstimateReq.java
  src/main/java/ddog/daengleserver/presentation/estimate/dto/request/UserDesignationGroomingEstimateReq.java
  src/main/java/ddog/daengleserver/presentation/estimate/dto/request/UserGeneralGroomingEstimateReq.java
  src/main/java/ddog/daengleserver/presentation/estimate/dto/response/UserAndPetsInfo.java
  src/main/java/ddog/daengleserver/presentation/estimate/dto/response/UserGroomingEstimateDetails.java
  src/main/java/ddog/daengleserver/presentation/estimate/dto/response/UserGroomingEstimateInfo.java
  src/main/java/ddog/daengleserver/presentation/estimate/enums/GroomerEstimateControllerResp.java
  src/main/java/ddog/daengleserver/presentation/estimate/enums/GroomingEstimateControllerResp.java
  src/main/java/ddog/daengleserver/presentation/usecase/AccountUseCase.java
  src/main/java/ddog/daengleserver/presentation/user/GroomingEstimateController.java
Labels: 💻 기능, 🛠️ 리팩토링

#24 [feat/daengle-13] 결제 검증 로직 구현
  .gitignore
  Dockerfile
  build.gradle
  src/main/java/ddog/daengleserver/application/OrderService.java
  src/main/java/ddog/daengleserver/application/PaymentService.java
  src/main/java/ddog/daengleserver/application/repository/OrderRepository.java
  src/main/java/ddog/daengleserver/domain/Order.java
  src/main/java/ddog/daengleserver/domain/Payment.java
  src/main/java/ddog/daengleserver/domain/enums/OrderExceptionType.java
  src/main/java/ddog/daengleserver/domain/enums/PaymentExceptionType.java
  src/main/java/ddog/daengleserver/domain/exception/OrderException.java
  src/main/java/ddog/daengleserver/domain/exception/PaymentException.java
  src/main/java/ddog/daengleserver/global/auth/config/IamPortConfig.java
  src/main/java/ddog/daengleserver/global/auth/config/jwt/JwtAuthenticationFilter.java
  src/main/java/ddog/daengleserver/infrastructure/GroomerJpaRepository.java
  src/main/java/ddog/daengleserver/infrastructure/OrderJpaRepository.java
  src/main/java/ddog/daengleserver/infrastructure/OrderRepositoryImpl.java
  src/main/java/ddog/daengleserver/infrastructure/PaymentRepositoryImpl.java
  src/main/java/ddog/daengleserver/infrastructure/po/OrderJpaEntity.java
  src/main/java/ddog/daengleserver/infrastructure/po/PaymentJpaEntity.java
  src/main/java/ddog/daengleserver/presentation/OrderController.java
  src/main/java/ddog/daengleserver/presentation/PaymentController.java
  src/main/java/ddog/daengleserver/presentation/dto/request/PaymentCallbackReq.java
  src/main/java/ddog/daengleserver/presentation/dto/request/PostOrderReq.java
  src/main/java/ddog/daengleserver/presentation/dto/response/PaymentCallbackResp.java
  src/main/java/ddog/daengleserver/presentation/dto/response/PostOrderResp.java
  src/main/java/ddog/daengleserver/presentation/enums/PostOrderResp.java
  src/main/java/ddog/daengleserver/presentation/usecase/OrderUseCase.java
  src/main/java/ddog/daengleserver/presentation/usecase/PaymentUseCase.java
Labels: 💻 기능

#30 [refactoring/daengle-15] Order 주문 데이터 영속 방식 변경
  src/main/java/ddog/daengleserver/application/OrderService.java
  src/main/java/ddog/daengleserver/application/repository/PaymentRepository.java
  src/main/java/ddog/daengleserver/application/repository/PetRepository.java
  src/main/java/ddog/daengleserver/domain/Payment.java
  src/main/java/ddog/daengleserver/infrastructure/PaymentRepositoryImpl.java
Labels: 🛠️ 리팩토링

#33 [refactoring/daengle-17] 결제 관련 예외처리 방식 변경 + 결제 검증 로직 리펙터링
  src/main/java/ddog/daengleserver/application/PaymentService.java
  src/main/java/ddog/daengleserver/application/repository/OrderRepository.java
  src/main/java/ddog/daengleserver/domain/Payment.java
  src/main/java/ddog/daengleserver/infrastructure/OrderRepositoryImpl.java
  src/main/java/ddog/daengleserver/presentation/dto/response/PaymentCallbackResp.java
Labels: 🛠️ 리팩토링

#37 [refactoring/daengle-18] 전역 예외 처리 컨벤션 수정
  src/main/java/ddog/daengleserver/domain/enums/OrderExceptionType.java
  src/main/java/ddog/daengleserver/domain/enums/PaymentExceptionType.java
  src/main/java/ddog/daengleserver/domain/enums/UserExceptionType.java
  src/main/java/ddog/daengleserver/domain/exception/OrderException.java
  src/main/java/ddog/daengleserver/domain/exception/PaymentException.java
  src/main/java/ddog/daengleserver/domain/exception/UserException.java
  src/main/java/ddog/daengleserver/global/auth/exception/AuthException.java
  src/main/java/ddog/daengleserver/global/auth/exception/enums/AuthExceptionType.java
  src/main/java/ddog/daengleserver/global/exception/BadRequestException.java
  src/main/java/ddog/daengleserver/global/exception/CustomError.java
  src/main/java/ddog/daengleserver/global/exception/CustomRuntimeException.java
  src/main/java/ddog/daengleserver/global/exception/GlobalControllerAdvice.java
  src/main/java/ddog/daengleserver/global/exception/NotFoundException.java
  src/main/java/ddog/daengleserver/implementation/AccountException.java
  src/main/java/ddog/daengleserver/implementation/enums/AccountExceptionType.java
Labels: 🛠️ 리팩토링

#42 [release/daengle-21] dev-api.daengle.com CI/CD 구축 완료 테스트
  .github/workflows/dev-deploy.yml
  .github/workflows/dev-integration.yml
  .github/workflows/prod-deploy.yml
  .github/workflows/prod-integration.yml
  src/main/java/ddog/daengleserver/presentation/APITestController.java
Labels: 🐞 버그, release

#44 [release/daengle-22] 운영서버 CI/CD 구축
  .github/workflows/prod-deploy.yml
Labels: release

#46 [main] api.daengle.com 운영 서버 CI/CD 테스트 (트러블슈팅)
  src/main/java/ddog/daengleserver/presentation/APITestController.java
Labels: 🐞 버그, release

#32 [feat/daengle-11] Notification 알림 기본 구현
  .github/workflows/dev-integration.yml
  build.gradle
  src/main/java/ddog/daengleserver/application/NotificationService.java
  src/main/java/ddog/daengleserver/application/repository/NotificationRepository.java
  src/main/java/ddog/daengleserver/domain/Notification.java
  src/main/java/ddog/daengleserver/global/infra/redis/RedisConfig.java
  src/main/java/ddog/daengleserver/global/infra/redis/RedisMessageListener.java
  src/main/java/ddog/daengleserver/global/infra/sse/SseEmitterService.java
  src/main/java/ddog/daengleserver/infrastructure/NotificationJpaRepository.java
  src/main/java/ddog/daengleserver/infrastructure/NotificationRepositoryImpl.java
  src/main/java/ddog/daengleserver/infrastructure/po/NotificationJpaEntity.java
  src/main/java/ddog/daengleserver/presentation/NotificationController.java
  src/main/java/ddog/daengleserver/presentation/estimate/GroomerEstimateController.java
  src/main/java/ddog/daengleserver/presentation/notify/dto/NotificationReq.java
  src/main/java/ddog/daengleserver/presentation/notify/enums/NotifyType.java
  src/main/java/ddog/daengleserver/presentation/usecase/NotificationUsecase.java
  src/main/java/ddog/daengleserver/presentation/usecase/SseEmitterUsecase.java
  src/main/resources/application-test.yml
  src/test/java/ddog/daengleserver/notify/NotificationControllerTest.java
  src/test/java/ddog/daengleserver/notify/NotificationTest.java
Labels: 💻 기능

#50 [refactoring/daengle-23] 견적서 및 사용자 프로필 관련 요청-응답 DTO 변수명 변경
  src/main/java/ddog/daengleserver/application/CareEstimateService.java
  src/main/java/ddog/daengleserver/application/GroomingEstimateService.java
  src/main/java/ddog/daengleserver/application/UserAccountService.java
  src/main/java/ddog/daengleserver/application/UserService.java
  src/main/java/ddog/daengleserver/domain/account/Pet.java
  src/main/java/ddog/daengleserver/domain/account/User.java
  src/main/java/ddog/daengleserver/domain/account/enums/Breed.java
  src/main/java/ddog/daengleserver/domain/estimate/CareEstimate.java
  src/main/java/ddog/daengleserver/domain/estimate/GroomingEstimate.java
  src/main/java/ddog/daengleserver/infrastructure/PetJpaRepository.java
  src/main/java/ddog/daengleserver/infrastructure/PetRepositoryImpl.java
  src/main/java/ddog/daengleserver/infrastructure/po/PetJpaEntity.java
  src/main/java/ddog/daengleserver/infrastructure/po/UserJpaEntity.java
  src/main/java/ddog/daengleserver/presentation/APITestController.java
  src/main/java/ddog/daengleserver/presentation/account/UserAccountController.java
  src/main/java/ddog/daengleserver/presentation/account/dto/request/AddPetInfo.java
  src/main/java/ddog/daengleserver/presentation/account/dto/request/JoinUserWithPet.java
  src/main/java/ddog/daengleserver/presentation/account/dto/request/ModifyPetInfo.java
  src/main/java/ddog/daengleserver/presentation/account/dto/request/UserProfileModifyReq.java
  src/main/java/ddog/daengleserver/presentation/account/dto/response/BreedInfo.java
  src/main/java/ddog/daengleserver/presentation/account/dto/response/PetInfo.java
  src/main/java/ddog/daengleserver/presentation/account/dto/response/UserProfileInfo.java
  src/main/java/ddog/daengleserver/presentation/account/enums/UserAccountControllerResp.java
  src/main/java/ddog/daengleserver/presentation/estimate/GroomerEstimateController.java
  src/main/java/ddog/daengleserver/presentation/estimate/UserEstimateController.java
  src/main/java/ddog/daengleserver/presentation/estimate/VetEstimateController.java
  src/main/java/ddog/daengleserver/presentation/estimate/dto/request/GroomerGroomingEstimateReq.java
  src/main/java/ddog/daengleserver/presentation/estimate/dto/request/UserDesignationCareEstimateReq.java
  src/main/java/ddog/daengleserver/presentation/estimate/dto/request/UserDesignationGroomingEstimateReq.java
  src/main/java/ddog/daengleserver/presentation/estimate/dto/request/UserGeneralCareEstimateReq.java
  src/main/java/ddog/daengleserver/presentation/estimate/dto/request/UserGeneralGroomingEstimateReq.java
  src/main/java/ddog/daengleserver/presentation/estimate/dto/request/VetCareEstimateReq.java
  src/main/java/ddog/daengleserver/presentation/estimate/dto/response/CareEstimateDetail.java
  src/main/java/ddog/daengleserver/presentation/estimate/dto/response/CareEstimateInfo.java
  src/main/java/ddog/daengleserver/presentation/estimate/dto/response/EstimateInfo.java
  src/main/java/ddog/daengleserver/presentation/estimate/dto/response/GroomingEstimateDetail.java
  src/main/java/ddog/daengleserver/presentation/estimate/dto/response/GroomingEstimateInfo.java
  src/main/java/ddog/daengleserver/presentation/estimate/dto/response/UserCareEstimateDetail.java
  src/main/java/ddog/daengleserver/presentation/estimate/dto/response/UserGroomingEstimateDetail.java
  src/main/java/ddog/daengleserver/presentation/estimate/dto/response/UserInfo.java
Labels: 🛠️ 리팩토링

#59 [sub/auth-1] 시큐리티, 인증 및 인가 관련 모듈 리팩티링 완료
  build.gradle
  daengle-auth/build.gradle
  daengle-auth/src/main/java/ddog/auth/application/KakaoSocialService.java
  daengle-auth/src/main/java/ddog/auth/application/OAuthService.java
  daengle-auth/src/main/java/ddog/auth/config/jwt/JwtTokenProvider.java
  daengle-auth/src/main/java/ddog/auth/dto/LoginResult.java
  daengle-auth/src/main/java/ddog/auth/dto/TokenAccountInfoDto.java
  daengle-auth/src/main/java/ddog/auth/exception/AuthException.java
  daengle-auth/src/main/java/ddog/auth/exception/AuthExceptionType.java
  daengle-auth/src/main/java/ddog/auth/exception/common/BadRequestException.java
  daengle-auth/src/main/java/ddog/auth/exception/common/CommonResponseEntity.java
  daengle-auth/src/main/java/ddog/auth/exception/common/CustomError.java
  daengle-auth/src/main/java/ddog/auth/exception/common/CustomRuntimeException.java
  daengle-auth/src/main/java/ddog/auth/exception/common/GlobalControllerAdvice.java
  daengle-auth/src/main/java/ddog/auth/exception/common/IllegalParameterException.java
  daengle-auth/src/main/java/ddog/auth/exception/common/NotFoundException.java
  daengle-auth/src/main/java/ddog/auth/presentation/OAuthController.java
  daengle-auth/src/main/java/ddog/auth/resolver/PayloadArgumentResolver.java
  daengle-domain/src/main/java/ddog/domain/enums/UserExceptionType.java
Labels: 🛠️ 리팩토링

#61 Sub/auth 2
  .github/workflows/dev-deploy.yml
  daengle-auth/src/main/java/ddog/auth/exception/common/BadRequestException.java
  daengle-auth/src/main/java/ddog/auth/exception/common/CommonResponseEntity.java
  daengle-auth/src/main/java/ddog/auth/exception/common/CustomError.java
  daengle-auth/src/main/java/ddog/auth/exception/common/CustomRuntimeException.java
  daengle-auth/src/main/java/ddog/auth/exception/common/GlobalControllerAdvice.java
  daengle-auth/src/main/java/ddog/auth/exception/common/IllegalParameterException.java
  daengle-auth/src/main/java/ddog/auth/exception/common/NotFoundException.java
  daengle-auth/src/main/java/ddog/auth/resolver/PayloadArgumentResolver.java
  daengle-groomer-api/src/main/java/ddog/groomer/application/auth/AuthService.java
  daengle-groomer-api/src/main/java/ddog/groomer/application/auth/KakaoSocialService.java
  daengle-groomer-api/src/main/java/ddog/groomer/application/exception/common/AuthException.java
  daengle-groomer-api/src/main/java/ddog/groomer/application/exception/common/AuthExceptionType.java
  daengle-groomer-api/src/main/java/ddog/groomer/presentation/AuthController.java
  daengle-payment-api/build.gradle
  daengle-payment-api/src/main/java/ddog/PaymentApplication.java
  daengle-payment-api/src/main/java/ddog/payment/application/auth/AuthService.java
  daengle-payment-api/src/main/java/ddog/payment/application/auth/KakaoSocialService.java
  daengle-payment-api/src/main/java/ddog/payment/application/exception/common/AuthException.java
  daengle-payment-api/src/main/java/ddog/payment/application/exception/common/AuthExceptionType.java
  daengle-payment-api/src/main/java/ddog/payment/presentation/AuthController.java
  daengle-payment-api/src/main/java/ddog/payment/presentation/OrderController.java
  daengle-persistence/src/main/java/ddog/persistence/adapter/NotificationRepository.java
  daengle-persistence/src/main/java/ddog/persistence/jpa/entity/NotificationJpaEntity.java
  daengle-persistence/src/main/java/ddog/persistence/jpa/repository/NotificationJpaRepository.java
  daengle-persistence/src/main/java/ddog/persistence/port/NotificationPersist.java
  daengle-user-api/src/main/java/ddog/user/application/auth/AuthService.java
  daengle-user-api/src/main/java/ddog/user/application/auth/KakaoSocialService.java
  daengle-user-api/src/main/java/ddog/user/application/exception/common/AuthException.java
  daengle-user-api/src/main/java/ddog/user/application/exception/common/AuthExceptionType.java
  daengle-user-api/src/main/java/ddog/user/presentation/AuthController.java
  daengle-vet-api/src/main/java/ddog/vet/application/auth/AuthService.java
  daengle-vet-api/src/main/java/ddog/vet/application/auth/KakaoSocialService.java
  daengle-vet-api/src/main/java/ddog/vet/application/exception/common/AuthException.java
  daengle-vet-api/src/main/java/ddog/vet/application/exception/common/AuthExceptionType.java
  daengle-vet-api/src/main/java/ddog/vet/presentation/AuthController.java
Labels: 🛠️ 리팩토링

#62 [sub/notification-1] 알림 모듈 분리 및 설계 기초 작업 (애플리케이션 모듈 ❌ 라이브러리 모듈 ✔️)
  build.gradle
  daengle-domain/src/main/java/ddog/domain/notification/Notification.java
  daengle-domain/src/main/java/ddog/domain/notification/NotificationReq.java
  daengle-notification/build.gradle
  daengle-notification/src/main/java/ddog/notification/application/NotificationService.java
  daengle-notification/src/main/java/ddog/notification/application/RedisMessageListener.java
  daengle-notification/src/main/java/ddog/notification/application/SseEmitterService.java
  daengle-notification/src/main/java/ddog/notification/application/config/RedisConfig.java
  daengle-payment-api/Dockerfile
  daengle-payment-api/compose.yml
  daengle-payment-api/src/main/java/ddog/payment/presentation/APITestController.java
  settings.gradle
  src/main/java/ddog/daengleserver/global/infra/swagger/config/SwaggerConfig.java
  src/main/java/ddog/daengleserver/presentation/NotificationController.java
  src/main/java/ddog/daengleserver/presentation/usecase/NotificationUsecase.java
  src/main/java/ddog/daengleserver/presentation/usecase/SseEmitterUsecase.java
  src/main/resources/application-test.yml
Labels: 🛠️ 리팩토링
