Repository DDog-org/daengle-server, pull requests merged in 2024-12, with the labels that each got.

#67 [refactoring/daengle-27] 웹 푸시 알림 리팩터링 및 모듈화 진행
  daengle-domain/src/main/java/ddog/domain/notification/Notification.java
  daengle-domain/src/main/java/ddog/domain/notification/NotificationReq.java
  daengle-domain/src/main/java/ddog/domain/notification/enums/NotifyType.java
  daengle-groomer-api/build.gradle
  daengle-groomer-api/src/main/java/ddog/groomer/presentation/estimate/EstimateController.java
  daengle-groomer-api/src/main/java/ddog/groomer/presentation/notification/NotificationController.java
  daengle-notification/build.gradle
  daengle-notification/src/main/java/ddog/notification/application/NotificationService.java
  daengle-notification/src/main/java/ddog/notification/application/RedisMessageListener.java
  daengle-notification/src/main/java/ddog/notification/application/RedisService.java
  daengle-notification/src/main/java/ddog/notification/application/SseEmitterService.java
  daengle-notification/src/main/java/ddog/notification/application/config/RedisConfig.java
  daengle-payment-api/build.gradle
  daengle-payment-api/src/main/java/ddog/payment/presentation/notification/NotificationController.java
  daengle-persistence/src/main/java/ddog/persistence/jpa/entity/NotificationJpaEntity.java
  daengle-user-api/build.gradle
  daengle-user-api/src/main/java/ddog/user/presentation/estimate/EstimateController.java
  daengle-user-api/src/main/java/ddog/user/presentation/notification/NotificationController.java
  daengle-vet-api/build.gradle
  daengle-vet-api/src/main/java/ddog/vet/presentation/notification/NotificationController.java
Labels: 🛠️ 리팩토링

#75 [refactoring/daengle-31] 견적서 관련 API 기능 변경에 따른 코드 보완
  daengle-domain/src/main/java/ddog/domain/pet/Part.java
  daengle-domain/src/main/java/ddog/domain/pet/Pet.java
  daengle-domain/src/main/java/ddog/domain/pet/SignificantTag.java
  daengle-groomer-api/src/main/java/ddog/groomer/presentation/account/AccountController.java
  daengle-persistence/src/main/java/ddog/persistence/jpa/entity/PetJpaEntity.java
  daengle-user-api/src/main/java/ddog/user/application/AccountService.java
  daengle-user-api/src/main/java/ddog/user/application/EstimateService.java
  daengle-user-api/src/main/java/ddog/user/application/mapper/CareEstimateMapper.java
  daengle-user-api/src/main/java/ddog/user/application/mapper/GroomingEstimateMapper.java
  daengle-user-api/src/main/java/ddog/user/application/mapper/PetMapper.java
  daengle-user-api/src/main/java/ddog/user/application/mapper/UserMapper.java
  daengle-user-api/src/main/java/ddog/user/presentation/account/AccountController.java
  daengle-user-api/src/main/java/ddog/user/presentation/account/dto/AddPetInfo.java
  daengle-user-api/src/main/java/ddog/user/presentation/account/dto/ModifyPetInfo.java
  daengle-user-api/src/main/java/ddog/user/presentation/account/dto/PetInfo.java
  daengle-user-api/src/main/java/ddog/user/presentation/account/dto/UserInfo.java
  daengle-user-api/src/main/java/ddog/user/presentation/estimate/EstimateController.java
  daengle-user-api/src/main/java/ddog/user/presentation/estimate/EstimateControllerResp.java
  daengle-user-api/src/main/java/ddog/user/presentation/estimate/dto/AccountInfo.java
  daengle-user-api/src/main/java/ddog/user/presentation/estimate/dto/CareEstimateReq.java
  daengle-user-api/src/main/java/ddog/user/presentation/estimate/dto/EstimateInfo.java
  daengle-user-api/src/main/java/ddog/user/presentation/estimate/dto/GeneralCareEstimateReq.java
  daengle-user-api/src/main/java/ddog/user/presentation/estimate/dto/GeneralGroomingEstimateReq.java
  daengle-user-api/src/main/java/ddog/user/presentation/estimate/dto/GroomerInfoReq.java
  daengle-user-api/src/main/java/ddog/user/presentation/estimate/dto/GroomingEstimateReq.java
  daengle-user-api/src/main/java/ddog/user/presentation/estimate/dto/VetInfoReq.java
  daengle-vet-api/src/main/java/ddog/vet/presentation/account/AccountController.java
Labels: 💻 기능, 🛠️ 리팩토링

#74 [feat/daengle-28] 카카오 알림톡 서비스 코드 추가
  daengle-notification/src/main/java/ddog/notification/application/KakaoNotificationService.java
  daengle-user-api/src/main/java/ddog/user/presentation/estimate/EstimateController.java
  src/test/java/ddog/daengleserver/notify/NotificationControllerTest.java
Labels: 💻 기능

#79 [refactoring/daengle-34] 사용자 등록 API 유효성 검사 로직 구현 및 예외 헨들링
  daengle-domain/src/main/java/ddog/domain/account/Account.java
  daengle-domain/src/main/java/ddog/domain/pet/Pet.java
  daengle-user-api/src/main/java/ddog/user/application/AccountService.java
  daengle-user-api/src/main/java/ddog/user/application/exception/AccountExceptionType.java
  daengle-user-api/src/main/java/ddog/user/application/exception/common/GlobalControllerAdvice.java
Labels: 🐞 버그, 🛠️ 리팩토링

#82 [feat/daengle-32] refreshToken을 활용한 accessToken 발급 로직 구현
  daengle-auth/src/main/java/ddog/auth/config/SecurityConfig.java
  daengle-auth/src/main/java/ddog/auth/config/jwt/JwtAccessDeniedHandler.java
  daengle-auth/src/main/java/ddog/auth/config/jwt/JwtAuthenticationEntryPoint.java
  daengle-auth/src/main/java/ddog/auth/config/jwt/JwtAuthenticationFilter.java
  daengle-auth/src/main/java/ddog/auth/config/jwt/JwtTokenProvider.java
  daengle-auth/src/main/java/ddog/auth/dto/AccessTokenInfo.java
  daengle-auth/src/main/java/ddog/auth/exception/AuthException.java
  daengle-auth/src/main/java/ddog/auth/exception/AuthExceptionType.java
  daengle-auth/src/main/java/ddog/auth/exception/common/BadRequestException.java
  daengle-auth/src/main/java/ddog/auth/exception/common/CommonResponseEntity.java
  daengle-auth/src/main/java/ddog/auth/exception/common/CustomError.java
  daengle-auth/src/main/java/ddog/auth/exception/common/CustomRuntimeException.java
  daengle-auth/src/main/java/ddog/auth/exception/common/GlobalControllerAdvice.java
  daengle-auth/src/main/java/ddog/auth/exception/common/IllegalParameterException.java
  daengle-auth/src/main/java/ddog/auth/exception/common/NotFoundException.java
  daengle-groomer-api/src/main/java/ddog/groomer/application/auth/AuthService.java
  daengle-groomer-api/src/main/java/ddog/groomer/application/auth/KakaoSocialService.java
  daengle-groomer-api/src/main/java/ddog/groomer/application/exception/common/AuthException.java
  daengle-groomer-api/src/main/java/ddog/groomer/application/exception/common/AuthExceptionType.java
  daengle-groomer-api/src/main/java/ddog/groomer/presentation/auth/AuthController.java
  daengle-payment-api/src/main/java/ddog/payment/application/auth/AuthService.java
  daengle-payment-api/src/main/java/ddog/payment/application/auth/KakaoSocialService.java
  daengle-payment-api/src/main/java/ddog/payment/application/exception/common/AuthExceptionType.java
  daengle-payment-api/src/main/java/ddog/payment/application/exception/common/GlobalControllerAdvice.java
  daengle-payment-api/src/main/java/ddog/payment/presentation/AuthController.java
  daengle-user-api/src/main/java/ddog/user/application/auth/AuthService.java
  daengle-user-api/src/main/java/ddog/user/application/auth/KakaoSocialService.java
  daengle-user-api/src/main/java/ddog/user/application/exception/common/AuthException.java
  daengle-user-api/src/main/java/ddog/user/application/exception/common/AuthExceptionType.java
  daengle-user-api/src/main/java/ddog/user/application/exception/common/GlobalControllerAdvice.java
  daengle-user-api/src/main/java/ddog/user/presentation/auth/AuthController.java
  daengle-vet-api/src/main/java/ddog/vet/application/auth/AuthService.java
  daengle-vet-api/src/main/java/ddog/vet/application/auth/KakaoSocialService.java
  daengle-vet-api/src/main/java/ddog/vet/application/exception/common/AuthException.java
  daengle-vet-api/src/main/java/ddog/vet/application/exception/common/AuthExceptionType.java
  daengle-vet-api/src/main/java/ddog/vet/application/exception/common/GlobalControllerAdvice.java
  daengle-vet-api/src/main/java/ddog/vet/presentation/auth/AuthController.java
Labels: 🐞 버그, 💻 기능, 🛠️ 리팩토링

#86 [refactoring/daengle-37] 유저/미용사/수의사 프로필 정보 변경 API 요청 데이터 유효성 검사 로직 구현
  daengle-domain/src/main/java/ddog/domain/groomer/Groomer.java
  daengle-domain/src/main/java/ddog/domain/pet/Pet.java
  daengle-domain/src/main/java/ddog/domain/vet/Vet.java
  daengle-groomer-api/src/main/java/ddog/groomer/application/AccountService.java
  daengle-groomer-api/src/main/java/ddog/groomer/application/exception/AccountException.java
  daengle-groomer-api/src/main/java/ddog/groomer/application/exception/GroomerException.java
  daengle-groomer-api/src/main/java/ddog/groomer/application/exception/common/BadRequestException.java
  daengle-groomer-api/src/main/java/ddog/groomer/application/exception/common/CommonResponseEntity.java
  daengle-groomer-api/src/main/java/ddog/groomer/application/exception/common/CustomError.java
  daengle-groomer-api/src/main/java/ddog/groomer/application/exception/common/CustomRuntimeException.java
  daengle-groomer-api/src/main/java/ddog/groomer/application/exception/common/IllegalParameterException.java
  daengle-groomer-api/src/main/java/ddog/groomer/application/exception/common/NotFoundException.java
  daengle-groomer-api/src/main/java/ddog/groomer/presentation/account/AccountController.java
  daengle-groomer-api/src/main/java/ddog/groomer/presentation/auth/AuthController.java
  daengle-groomer-api/src/main/java/ddog/groomer/presentation/estimate/EstimateController.java
  daengle-payment-api/src/main/java/ddog/payment/application/exception/OrderException.java
  daengle-payment-api/src/main/java/ddog/payment/application/exception/PaymentException.java
  daengle-payment-api/src/main/java/ddog/payment/application/exception/common/BadRequestException.java
  daengle-payment-api/src/main/java/ddog/payment/application/exception/common/CommonResponseEntity.java
  daengle-payment-api/src/main/java/ddog/payment/application/exception/common/CustomError.java
  daengle-payment-api/src/main/java/ddog/payment/application/exception/common/CustomRuntimeException.java
  daengle-payment-api/src/main/java/ddog/payment/application/exception/common/IllegalParameterException.java
  daengle-payment-api/src/main/java/ddog/payment/application/exception/common/NotFoundException.java
  daengle-user-api/src/main/java/ddog/user/application/AccountService.java
  daengle-user-api/src/main/java/ddog/user/application/exception/AccountException.java
  daengle-user-api/src/main/java/ddog/user/application/exception/UserException.java
  daengle-user-api/src/main/java/ddog/user/application/exception/common/BadRequestException.java
  daengle-user-api/src/main/java/ddog/user/application/exception/common/CommonResponseEntity.java
  daengle-user-api/src/main/java/ddog/user/application/exception/common/CustomError.java
  daengle-user-api/src/main/java/ddog/user/application/exception/common/CustomRuntimeException.java
  daengle-user-api/src/main/java/ddog/user/application/exception/common/IllegalParameterException.java
  daengle-user-api/src/main/java/ddog/user/application/exception/common/NotFoundException.java
  daengle-user-api/src/main/java/ddog/user/presentation/account/AccountController.java
  daengle-user-api/src/main/java/ddog/user/presentation/account/dto/UserInfoModifyReq.java
  daengle-vet-api/src/main/java/ddog/vet/application/AccountService.java
  daengle-vet-api/src/main/java/ddog/vet/application/exception/VetException.java
  daengle-vet-api/src/main/java/ddog/vet/application/exception/common/BadRequestException.java
  daengle-vet-api/src/main/java/ddog/vet/application/exception/common/CommonResponseEntity.java
  daengle-vet-api/src/main/java/ddog/vet/application/exception/common/CustomError.java
  daengle-vet-api/src/main/java/ddog/vet/application/exception/common/CustomRuntimeException.java
  daengle-vet-api/src/main/java/ddog/vet/application/exception/common/IllegalParameterException.java
  daengle-vet-api/src/main/java/ddog/vet/application/exception/common/NotFoundException.java
  daengle-vet-api/src/main/java/ddog/vet/presentation/account/AccountController.java
  daengle-vet-api/src/main/java/ddog/vet/presentation/auth/AuthController.java
  daengle-vet-api/src/main/java/ddog/vet/presentation/estimate/EstimateController.java
Labels: 🛠️ 리팩토링

#87 [refactoring/daengle-36] 견적서 API 유효성 검사 로직 구현 및 리팩토링
  daengle-auth/src/main/java/ddog/auth/exception/common/GlobalControllerAdvice.java
  daengle-domain/src/main/java/ddog/domain/estimate/CareEstimate.java
  daengle-domain/src/main/java/ddog/domain/estimate/GroomingEstimate.java
  daengle-domain/src/main/java/ddog/domain/pet/Pet.java
  daengle-groomer-api/src/main/java/ddog/groomer/application/AccountService.java
  daengle-groomer-api/src/main/java/ddog/groomer/application/EstimateService.java
  daengle-groomer-api/src/main/java/ddog/groomer/application/mapper/GroomingEstimateMapper.java
  daengle-groomer-api/src/main/java/ddog/groomer/presentation/account/AccountController.java
  daengle-groomer-api/src/main/java/ddog/groomer/presentation/account/dto/AccountResp.java
  daengle-groomer-api/src/main/java/ddog/groomer/presentation/estimate/EstimateController.java
  daengle-groomer-api/src/main/java/ddog/groomer/presentation/estimate/EstimateControllerResp.java
  daengle-groomer-api/src/main/java/ddog/groomer/presentation/estimate/dto/EstimateDetail.java
  daengle-groomer-api/src/main/java/ddog/groomer/presentation/estimate/dto/EstimateInfo.java
  daengle-groomer-api/src/main/java/ddog/groomer/presentation/estimate/dto/EstimateReq.java
  daengle-groomer-api/src/main/java/ddog/groomer/presentation/estimate/dto/EstimateResp.java
  daengle-persistence/src/main/java/ddog/persistence/adapter/PetRepository.java
  daengle-persistence/src/main/java/ddog/persistence/jpa/entity/CareEstimateJpaEntity.java
  daengle-persistence/src/main/java/ddog/persistence/jpa/entity/GroomingEstimateJpaEntity.java
  daengle-persistence/src/main/java/ddog/persistence/jpa/repository/PetJpaRepository.java
  daengle-persistence/src/main/java/ddog/persistence/port/PetPersist.java
  daengle-persistence/src/main/java/ddog/persistence/port/UserPersist.java
  daengle-user-api/src/main/java/ddog/user/application/AccountService.java
  daengle-user-api/src/main/java/ddog/user/application/EstimateService.java
  daengle-user-api/src/main/java/ddog/user/application/mapper/CareEstimateMapper.java
  daengle-user-api/src/main/java/ddog/user/application/mapper/GroomingEstimateMapper.java
  daengle-user-api/src/main/java/ddog/user/presentation/account/AccountController.java
  daengle-user-api/src/main/java/ddog/user/presentation/account/AccountControllerResp.java
  daengle-user-api/src/main/java/ddog/user/presentation/account/dto/AccountResp.java
  daengle-user-api/src/main/java/ddog/user/presentation/auth/AuthController.java
  daengle-user-api/src/main/java/ddog/user/presentation/estimate/EstimateController.java
  daengle-user-api/src/main/java/ddog/user/presentation/estimate/EstimateControllerResp.java
  daengle-user-api/src/main/java/ddog/user/presentation/estimate/dto/AccountInfo.java
  daengle-user-api/src/main/java/ddog/user/presentation/estimate/dto/CareEstimateReq.java
  daengle-user-api/src/main/java/ddog/user/presentation/estimate/dto/EstimateResp.java
  daengle-user-api/src/main/java/ddog/user/presentation/estimate/dto/GroomingEstimateReq.java
  daengle-vet-api/src/main/java/ddog/vet/application/AccountService.java
  daengle-vet-api/src/main/java/ddog/vet/application/EstimateService.java
  daengle-vet-api/src/main/java/ddog/vet/application/mapper/CareEstimateMapper.java
  daengle-vet-api/src/main/java/ddog/vet/presentation/account/AccountController.java
  daengle-vet-api/src/main/java/ddog/vet/presentation/account/dto/AccountResp.java
  daengle-vet-api/src/main/java/ddog/vet/presentation/estimate/EstimateController.java
  daengle-vet-api/src/main/java/ddog/vet/presentation/estimate/EstimateControllerResp.java
  daengle-vet-api/src/main/java/ddog/vet/presentation/estimate/dto/EstimateDetail.java
  daengle-vet-api/src/main/java/ddog/vet/presentation/estimate/dto/EstimateInfo.java
  daengle-vet-api/src/main/java/ddog/vet/presentation/estimate/dto/EstimateReq.java
  daengle-vet-api/src/main/java/ddog/vet/presentation/estimate/dto/EstimateResp.java
Labels: 💻 기능, 🛠️ 리팩토링

#90 [feat/daengle-29] 채팅 관련 기본 설계
  daengle-chat-api/Dockerfile
  daengle-chat-api/build.gradle
  daengle-chat-api/src/main/java/ddog/ChatApplication.java
  daengle-chat-api/src/main/java/ddog/chat/application/ChatService.java
  daengle-chat-api/src/main/java/ddog/chat/application/config/DynamoDBConfig.java
  daengle-chat-api/src/main/java/ddog/chat/application/config/WebSocketConfig.java
  daengle-chat-api/src/main/java/ddog/chat/application/dto/request/ChatRoomReq.java
  daengle-chat-api/src/main/java/ddog/chat/presentation/ChatController.java
  daengle-domain/src/main/java/ddog/domain/chat/ChatMessage.java
  daengle-domain/src/main/java/ddog/domain/chat/ChatRoom.java
  daengle-domain/src/main/java/ddog/domain/chat/enums/ChatType.java
  daengle-persistence/build.gradle
  daengle-persistence/src/main/java/ddog/persistence/adapter/ChatMessageDynamoRepository.java
  daengle-persistence/src/main/java/ddog/persistence/adapter/ChatRoomRepository.java
  daengle-persistence/src/main/java/ddog/persistence/dynamo/entity/ChatMessageDynamoEntity.java
  daengle-persistence/src/main/java/ddog/persistence/jpa/entity/ChatRoomJpaEntity.java
  daengle-persistence/src/main/java/ddog/persistence/jpa/repository/ChatRoomJpaRepository.java
  daengle-persistence/src/main/java/ddog/persistence/port/ChatMessagePersist.java
  daengle-persistence/src/main/java/ddog/persistence/port/ChatRoomPersist.java
  settings.gradle
  src/test/java/ddog/daengleserver/DaengleServerApplicationTests.java
  src/test/java/ddog/daengleserver/notify/NotificationTest.java
Labels: 💻 기능

#93 [feat/daengle-40] 리뷰 도메인 엔티티 및 jpa 영속성 객체 구현
  daengle-domain/src/main/java/ddog/domain/groomer/Groomer.java
  daengle-domain/src/main/java/ddog/domain/review/CareReview.java
  daengle-domain/src/main/java/ddog/domain/review/GroomingReview.java
  daengle-domain/src/main/java/ddog/domain/review/Review.java
  daengle-domain/src/main/java/ddog/domain/review/enums/CareKeywordReview.java
  daengle-domain/src/main/java/ddog/domain/review/enums/GroomingKeywordReview.java
  daengle-domain/src/main/java/ddog/domain/user/User.java
  daengle-domain/src/main/java/ddog/domain/vet/Vet.java
  daengle-persistence/src/main/java/ddog/persistence/jpa/entity/CareReviewJpaEntity.java
  daengle-persistence/src/main/java/ddog/persistence/jpa/entity/GroomerJpaEntity.java
  daengle-persistence/src/main/java/ddog/persistence/jpa/entity/GroomingReviewJpaEntity.java
Labels: 💻 기능, ‼️ 주목

#99 [feat/daengle-44] 예약 도메인 엔티티 설계
  daengle-domain/src/main/java/ddog/domain/order/Order.java
  daengle-domain/src/main/java/ddog/domain/order/enums/PostOrderReq.java
  daengle-domain/src/main/java/ddog/domain/payment/Order.java
  daengle-domain/src/main/java/ddog/domain/payment/Payment.java
  daengle-domain/src/main/java/ddog/domain/payment/Reservation.java
  daengle-domain/src/main/java/ddog/domain/payment/dto/PostOrderInfo.java
  daengle-domain/src/main/java/ddog/domain/payment/enums/ReservationStatus.java
  daengle-domain/src/main/java/ddog/domain/payment/enums/ServiceType.java
  daengle-groomer-api/src/main/java/ddog/groomer/Test.java
  daengle-payment-api/src/main/java/ddog/payment/application/OrderService.java
  daengle-payment-api/src/main/java/ddog/payment/application/PaymentService.java
  daengle-payment-api/src/main/java/ddog/payment/application/dto/request/PaymentCallbackReq.java
  daengle-payment-api/src/main/java/ddog/payment/application/dto/response/PaymentCallbackResp.java
  daengle-payment-api/src/main/java/ddog/payment/application/dto/response/PostOrderResp.java
  daengle-payment-api/src/main/java/ddog/payment/presentation/OrderController.java
  daengle-payment-api/src/main/java/ddog/payment/presentation/PaymentController.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/adapter/OrderRepository.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/adapter/ReservationRepository.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/jpa/entity/OrderJpaEntity.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/jpa/entity/PaymentJpaEntity.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/jpa/entity/ReservationJpaEntity.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/jpa/repository/ReservationJpaRepository.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/port/OrderPersist.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/port/ReservationPersist.java
Labels: 💻 기능

#92 [release/daengle-41] 멀티 모듈로 인한 모듈별 CI/CD 구축
  .github/workflows/dev-deploy.yml
  .github/workflows/dev-integration.yml
  .github/workflows/prod-deploy.yml
  .github/workflows/prod-integration.yml
  daengle-groomer-api/src/main/java/ddog/groomer/presentation/TestController.java
  daengle-payment-api/src/main/java/ddog/payment/presentation/TestController.java
  daengle-user-api/src/main/java/ddog/user/presentation/TestController.java
  daengle-vet-api/src/main/java/ddog/vet/presentation/TestController.java
Labels: release

#102 [feat/daengle-42] 리뷰 도메인 설계 및 기본 API 구현
  daengle-auth/src/main/java/ddog/auth/config/SecurityConfig.java
  daengle-domain/src/main/java/ddog/domain/groomer/GroomerDaengleMeter.java
  daengle-domain/src/main/java/ddog/domain/payment/Order.java
  daengle-domain/src/main/java/ddog/domain/payment/Reservation.java
  daengle-domain/src/main/java/ddog/domain/payment/dto/PostOrderInfo.java
  daengle-domain/src/main/java/ddog/domain/review/CareReview.java
  daengle-domain/src/main/java/ddog/domain/review/GroomingReview.java
  daengle-domain/src/main/java/ddog/domain/review/Review.java
  daengle-domain/src/main/java/ddog/domain/review/dto/ModifyCareReviewInfo.java
  daengle-domain/src/main/java/ddog/domain/review/dto/ModifyGroomingReviewInfo.java
  daengle-domain/src/main/java/ddog/domain/review/dto/PostCareReviewInfo.java
  daengle-domain/src/main/java/ddog/domain/review/dto/PostGroomingReviewInfo.java
  daengle-domain/src/main/java/ddog/domain/vet/VetDaengleMeter.java
  daengle-payment-api/src/main/java/ddog/payment/application/OrderService.java
  daengle-payment-api/src/main/java/ddog/payment/application/PaymentService.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/adapter/CareReviewRepository.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/adapter/EstimateRepository.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/adapter/GroomingEstimateLogRepository.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/adapter/GroomingReviewRepository.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/adapter/PaymentRepository.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/adapter/ReservationRepository.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/jpa/entity/CareReviewJpaEntity.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/jpa/entity/EstimateJpaEntity.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/jpa/entity/GroomerDanegleMeterJpaEntity.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/jpa/entity/GroomingReviewJpaEntity.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/jpa/entity/OrderJpaEntity.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/jpa/entity/PaymentJpaEntity.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/jpa/entity/ReservationJpaEntity.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/jpa/entity/VetDaengleMeterJpaEntity.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/jpa/entity/VetReviewJpaEntity.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/jpa/repository/CareReviewJpaRepository.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/jpa/repository/EstimateJpaRepository.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/jpa/repository/GroomingEstimateLogJpaRepository.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/jpa/repository/GroomingReviewJpaRepository.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/jpa/repository/ReservationJpaRepository.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/port/CareReviewPersist.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/port/EstimatePersist.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/port/GroomingReviewPersist.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/port/ReservationPersist.java
  daengle-user-api/src/main/java/ddog/user/application/CareReviewService.java
  daengle-user-api/src/main/java/ddog/user/application/GroomingReviewService.java
  daengle-user-api/src/main/java/ddog/user/application/ReservationService.java
  daengle-user-api/src/main/java/ddog/user/application/exception/ReservationException.java
  daengle-user-api/src/main/java/ddog/user/application/exception/ReservationExceptionType.java
  daengle-user-api/src/main/java/ddog/user/application/exception/ReviewException.java
  daengle-user-api/src/main/java/ddog/user/application/exception/ReviewExceptionType.java
  daengle-user-api/src/main/java/ddog/user/application/mapper/CareEstimateMapper.java
  daengle-user-api/src/main/java/ddog/user/application/mapper/GroomingEstimateMapper.java
  daengle-user-api/src/main/java/ddog/user/presentation/estimate/dto/CareEstimateDetail.java
  daengle-user-api/src/main/java/ddog/user/presentation/estimate/dto/GroomingEstimateDetail.java
  daengle-user-api/src/main/java/ddog/user/presentation/reservation/ReservationController.java
  daengle-user-api/src/main/java/ddog/user/presentation/reservation/dto/ReservationSummary.java
  daengle-user-api/src/main/java/ddog/user/presentation/review/CareReviewController.java
  daengle-user-api/src/main/java/ddog/user/presentation/review/GroomingController.java
  daengle-user-api/src/main/java/ddog/user/presentation/review/dto/ReviewResp.java
Labels: 💻 기능

#113 [feat/daengle-51] 서킷브레이커 패턴을 활용한 알림 서비스 타임아웃 설정
  build.gradle
  src/main/java/ddog/daengleserver/application/PaymentService.java
  src/main/java/ddog/daengleserver/domain/enums/PaymentExceptionType.java
  src/main/java/ddog/daengleserver/global/infra/resilience/Resilience4jConfig.java
  src/main/java/ddog/daengleserver/presentation/payment/OrderController.java
  src/main/java/ddog/daengleserver/presentation/payment/PaymentController.java
Labels: 💻 기능

#112 [feat/daengle-50] 모놀리식 아키텍처 서버 모니터링 환경 세팅
  build.gradle
Labels: 💻 기능

#114 [feat/daengle-52] 모놀로식 레포 & 단일 서버 환경에서의 외부 API(Kakao Solapi) 타임아웃 테스트 설정
  build.gradle
  src/main/java/ddog/daengleserver/application/CareEstimateService.java
  src/main/java/ddog/daengleserver/application/KakaoNotificationService.java
  src/main/java/ddog/daengleserver/application/repository/VetRepository.java
  src/main/java/ddog/daengleserver/domain/account/Vet.java
  src/main/java/ddog/daengleserver/infrastructure/VetJpaRepository.java
  src/main/java/ddog/daengleserver/infrastructure/VetRepositoryImpl.java
  src/main/java/ddog/daengleserver/infrastructure/po/VetJpaEntity.java
  src/main/java/ddog/daengleserver/presentation/NotificationController.java
  src/main/java/ddog/daengleserver/presentation/estimate/UserEstimateController.java
  src/main/java/ddog/daengleserver/presentation/notification/WebNotificationController.java
  src/test/java/ddog/daengleserver/notify/WebNotificationControllerTest.java
Labels: 💻 기능

#120 [feat/daengle-55] 주문 요청 데이터 유효성 검사 로직 구현
  daengle-domain/src/main/java/ddog/domain/payment/Order.java
  daengle-payment-api/src/main/java/ddog/payment/application/OrderService.java
  daengle-payment-api/src/main/java/ddog/payment/application/PaymentService.java
  daengle-payment-api/src/main/java/ddog/payment/presentation/DeployCheckController.java
Labels: 💻 기능

#122 [feat/daengle-56] 리뷰 작성 데이터 유효성 검사 로직 구현
  daengle-domain/src/main/java/ddog/domain/review/CareReview.java
  daengle-domain/src/main/java/ddog/domain/review/GroomingReview.java
  daengle-user-api/src/main/java/ddog/user/application/CareReviewService.java
  daengle-user-api/src/main/java/ddog/user/application/GroomingReviewService.java
Labels: 💻 기능

#126 [fix/daengle-59] 프론트엔드 배포 서버 CORS 에러 해결
  daengle-auth/src/main/java/ddog/auth/config/SecurityConfig.java
Labels: 🐞 버그, 🚨 핫픽스

#129 [refactoring/daengle-57] 포트-어댑터 패턴, Port 패키지 위치 변경
  daengle-auth/src/main/java/ddog/auth/config/jwt/JwtTokenProvider.java
  daengle-chat-api/build.gradle
  daengle-chat-api/src/main/java/ddog/chat/application/ChatService.java
  daengle-domain/build.gradle
  daengle-domain/src/main/java/ddog/domain/account/port/AccountPersist.java
  daengle-domain/src/main/java/ddog/domain/chat/port/ChatMessagePersist.java
  daengle-domain/src/main/java/ddog/domain/chat/port/ChatRoomPersist.java
  daengle-domain/src/main/java/ddog/domain/estimate/port/CareEstimatePersist.java
  daengle-domain/src/main/java/ddog/domain/estimate/port/GroomingEstimatePersist.java
  daengle-domain/src/main/java/ddog/domain/groomer/port/GroomerPersist.java
  daengle-domain/src/main/java/ddog/domain/notification/port/NotificationPersist.java
  daengle-domain/src/main/java/ddog/domain/payment/port/OrderPersist.java
  daengle-domain/src/main/java/ddog/domain/payment/port/PaymentPersist.java
  daengle-domain/src/main/java/ddog/domain/payment/port/ReservationPersist.java
  daengle-domain/src/main/java/ddog/domain/pet/port/PetPersist.java
  daengle-domain/src/main/java/ddog/domain/review/port/CareReviewPersist.java
  daengle-domain/src/main/java/ddog/domain/review/port/GroomingReviewPersist.java
  daengle-domain/src/main/java/ddog/domain/user/port/UserPersist.java
  daengle-domain/src/main/java/ddog/domain/vet/port/VetPersist.java
  daengle-groomer-api/build.gradle
  daengle-groomer-api/src/main/java/ddog/groomer/application/AccountService.java
  daengle-groomer-api/src/main/java/ddog/groomer/application/EstimateService.java
  daengle-groomer-api/src/main/java/ddog/groomer/application/ReviewService.java
  daengle-groomer-api/src/main/java/ddog/groomer/application/auth/AuthService.java
  daengle-notification/src/main/java/ddog/notification/application/NotificationService.java
  daengle-payment-api/build.gradle
  daengle-payment-api/src/main/java/ddog/payment/application/OrderService.java
  daengle-payment-api/src/main/java/ddog/payment/application/PaymentService.java
  daengle-persistence-dynamodb/build.gradle
  daengle-persistence-dynamodb/src/main/java/ddog/persistence/dynamodb/adapter/ChatMessageDynamoRepository.java
  daengle-persistence-dynamodb/src/main/java/ddog/persistence/dynamodb/entity/ChatMessageDynamoEntity.java
  daengle-persistence-mysql/build.gradle
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/adapter/AccountRepository.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/adapter/CareEstimateRepository.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/adapter/CareReviewRepository.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/adapter/ChatRoomRepository.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/adapter/GroomerRepository.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/adapter/GroomingEstimateRepository.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/adapter/GroomingReviewRepository.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/adapter/NotificationRepository.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/adapter/OrderRepository.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/adapter/PaymentRepository.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/adapter/PetRepository.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/adapter/ReservationRepository.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/adapter/UserRepository.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/adapter/VetRepository.java
  daengle-user-api/build.gradle
  daengle-user-api/src/main/java/ddog/user/application/AccountService.java
  daengle-user-api/src/main/java/ddog/user/application/CareReviewService.java
  daengle-user-api/src/main/java/ddog/user/application/EstimateService.java
  daengle-user-api/src/main/java/ddog/user/application/GroomingReviewService.java
  daengle-user-api/src/main/java/ddog/user/application/ReservationService.java
  daengle-user-api/src/main/java/ddog/user/application/auth/AuthService.java
  daengle-vet-api/build.gradle
  daengle-vet-api/src/main/java/ddog/vet/application/AccountService.java
  daengle-vet-api/src/main/java/ddog/vet/application/EstimateService.java
  daengle-vet-api/src/main/java/ddog/vet/application/ReviewService.java
  daengle-vet-api/src/main/java/ddog/vet/application/auth/AuthService.java
Labels: 🛠️ 리팩토링

#130 [refactoring/daengle-58] 코드 컨벤션 통일 (정적 팩터리 메서드, findBy)
  daengle-domain/src/main/java/ddog/domain/groomer/port/GroomerPersist.java
  daengle-domain/src/main/java/ddog/domain/payment/Order.java
  daengle-domain/src/main/java/ddog/domain/payment/Payment.java
  daengle-domain/src/main/java/ddog/domain/payment/port/OrderPersist.java
  daengle-domain/src/main/java/ddog/domain/payment/port/ReservationPersist.java
  daengle-domain/src/main/java/ddog/domain/review/CareReview.java
  daengle-domain/src/main/java/ddog/domain/review/GroomingReview.java
  daengle-domain/src/main/java/ddog/domain/review/Review.java
  daengle-domain/src/main/java/ddog/domain/review/port/CareReviewPersist.java
  daengle-domain/src/main/java/ddog/domain/review/port/GroomingReviewPersist.java
  daengle-domain/src/main/java/ddog/domain/user/port/UserPersist.java
  daengle-domain/src/main/java/ddog/domain/vet/port/VetPersist.java
  daengle-groomer-api/src/main/java/ddog/groomer/application/ReviewService.java
  daengle-payment-api/src/main/java/ddog/payment/application/OrderService.java
  daengle-payment-api/src/main/java/ddog/payment/application/PaymentService.java
  daengle-payment-api/src/main/java/ddog/payment/application/mapper/OrderMapper.java
  daengle-payment-api/src/main/java/ddog/payment/application/mapper/PaymentMapper.java
  daengle-payment-api/src/main/java/ddog/payment/application/mapper/ReservationMapper.java
  daengle-payment-api/src/main/java/ddog/payment/presentation/OrderController.java
  daengle-payment-api/src/main/java/ddog/payment/presentation/dto/PostOrderInfo.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/adapter/CareReviewRepository.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/adapter/GroomerRepository.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/adapter/GroomingReviewRepository.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/adapter/OrderRepository.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/adapter/ReservationRepository.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/adapter/UserRepository.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/adapter/VetRepository.java
  daengle-user-api/src/main/java/ddog/user/application/CareReviewService.java
  daengle-user-api/src/main/java/ddog/user/application/GroomingReviewService.java
  daengle-user-api/src/main/java/ddog/user/application/ReservationService.java
  daengle-user-api/src/main/java/ddog/user/application/mapper/CareReviewMapper.java
  daengle-user-api/src/main/java/ddog/user/application/mapper/GroomingReviewMapper.java
  daengle-user-api/src/main/java/ddog/user/presentation/review/CareReviewController.java
  daengle-user-api/src/main/java/ddog/user/presentation/review/GroomingReviewController.java
  daengle-user-api/src/main/java/ddog/user/presentation/review/dto/ModifyCareReviewInfo.java
  daengle-user-api/src/main/java/ddog/user/presentation/review/dto/ModifyGroomingReviewInfo.java
  daengle-user-api/src/main/java/ddog/user/presentation/review/dto/PostCareReviewInfo.java
  daengle-user-api/src/main/java/ddog/user/presentation/review/dto/PostGroomingReviewInfo.java
  daengle-vet-api/src/main/java/ddog/vet/application/ReviewService.java
Labels: 🛠️ 리팩토링, ‼️ 주목

#139 [feat/daengle-65] 미용사/병원 전체 리뷰 조회 응답값 수정
  daengle-domain/src/main/java/ddog/domain/review/CareReview.java
  daengle-domain/src/main/java/ddog/domain/review/GroomingReview.java
  daengle-domain/src/main/java/ddog/domain/review/enums/CareKeywordReview.java
  daengle-domain/src/main/java/ddog/domain/review/enums/GroomingKeywordReview.java
  daengle-user-api/src/main/java/ddog/user/application/CareReviewService.java
  daengle-user-api/src/main/java/ddog/user/application/GroomingReviewService.java
  daengle-user-api/src/main/java/ddog/user/presentation/review/dto/response/CareReviewSummaryResp.java
  daengle-user-api/src/main/java/ddog/user/presentation/review/dto/response/GroomingReviewSummaryResp.java
Labels: 💻 기능

#134 [feat/daengle-61] Spring Security 및 로그인/온보딩 유효성 검사 과정 추가 커스텀 에러 추가
  daengle-auth/src/main/java/ddog/auth/config/SecurityConfig.java
  daengle-auth/src/main/java/ddog/auth/config/jwt/JwtAuthenticationFilter.java
  daengle-auth/src/main/java/ddog/auth/config/jwt/JwtTokenProvider.java
  daengle-auth/src/main/java/ddog/auth/exception/AuthExceptionType.java
  daengle-domain/src/main/java/ddog/domain/account/port/AccountPersist.java
  daengle-groomer-api/src/main/java/ddog/groomer/application/auth/AuthService.java
  daengle-groomer-api/src/main/java/ddog/groomer/application/exception/account/AccountExceptionType.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/adapter/AccountRepository.java
  daengle-user-api/src/main/java/ddog/user/application/auth/AuthService.java
  daengle-user-api/src/main/java/ddog/user/application/exception/account/AccountExceptionType.java
  daengle-user-api/src/main/java/ddog/user/presentation/DeployCheckController.java
  daengle-user-api/src/main/java/ddog/user/presentation/TokenReq.java
  daengle-vet-api/src/main/java/ddog/vet/application/auth/AuthService.java
  daengle-vet-api/src/main/java/ddog/vet/application/exception/account/AccountExceptionType.java
Labels: 💻 기능, 🛠️ 리팩토링

#135 [feat/daengle-62] 금칙어 필터링 시스템 v1 구현 완료
  build.gradle
  daengle-user-api/build.gradle
  daengle-user-api/src/main/java/ddog/user/application/CareReviewService.java
  daengle-user-api/src/main/java/ddog/user/application/GroomingReviewService.java
  daengle-user-api/src/main/java/ddog/user/application/config/BadWordFilteringConfig.java
  daengle-user-api/src/main/java/ddog/user/application/exception/ReviewExceptionType.java
  daengle-user-api/src/test/java/ReviewBanWordFilteringPerformanceTest.java
  daengle-user-api/src/test/java/ReviewBanWordFilteringTest.java
  daengle-user-api/src/test/resources/badReviews.txt
  daengle-user-api/src/test/resources/banwords.txt
  daengle-user-api/src/test/resources/cleanReviews.txt
Labels: 💻 기능, 😢 이슈

#144 [feat/daengle-64] 기존 견적서 API 조회 관련 페이징 기능 추가
  daengle-domain/src/main/java/ddog/domain/estimate/port/CareEstimatePersist.java
  daengle-domain/src/main/java/ddog/domain/estimate/port/GroomingEstimatePersist.java
  daengle-domain/src/main/java/ddog/domain/groomer/Groomer.java
  daengle-domain/src/main/java/ddog/domain/groomer/enums/GroomingKeyword.java
  daengle-domain/src/main/java/ddog/domain/review/CareReview.java
  daengle-domain/src/main/java/ddog/domain/review/GroomingReview.java
  daengle-domain/src/main/java/ddog/domain/vet/Vet.java
  daengle-domain/src/main/java/ddog/domain/vet/enums/CareKeyword.java
  daengle-groomer-api/src/main/java/ddog/groomer/application/EstimateService.java
  daengle-groomer-api/src/main/java/ddog/groomer/application/ReviewService.java
  daengle-groomer-api/src/main/java/ddog/groomer/presentation/estimate/dto/EstimateInfo.java
  daengle-groomer-api/src/main/java/ddog/groomer/presentation/review/dto/ReviewSummaryResp.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/adapter/CareEstimateRepository.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/adapter/GroomingEstimateRepository.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/jpa/entity/CareReviewJpaEntity.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/jpa/entity/GroomerJpaEntity.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/jpa/entity/GroomingReviewJpaEntity.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/jpa/entity/VetJpaEntity.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/jpa/repository/CareEstimateJpaRepository.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/jpa/repository/GroomingEstimateJpaRepository.java
  daengle-user-api/src/main/java/ddog/user/application/CareReviewService.java
  daengle-user-api/src/main/java/ddog/user/application/EstimateService.java
  daengle-user-api/src/main/java/ddog/user/application/GroomingReviewService.java
  daengle-user-api/src/main/java/ddog/user/application/mapper/CareEstimateMapper.java
  daengle-user-api/src/main/java/ddog/user/application/mapper/CareReviewMapper.java
  daengle-user-api/src/main/java/ddog/user/application/mapper/GroomingEstimateMapper.java
  daengle-user-api/src/main/java/ddog/user/application/mapper/GroomingReviewMapper.java
  daengle-user-api/src/main/java/ddog/user/application/mapper/PetMapper.java
  daengle-user-api/src/main/java/ddog/user/presentation/estimate/EstimateController.java
  daengle-user-api/src/main/java/ddog/user/presentation/estimate/dto/EstimateInfo.java
  daengle-user-api/src/main/java/ddog/user/presentation/review/dto/request/ModifyCareReviewInfo.java
  daengle-user-api/src/main/java/ddog/user/presentation/review/dto/request/ModifyGroomingReviewInfo.java
  daengle-user-api/src/main/java/ddog/user/presentation/review/dto/request/PostCareReviewInfo.java
  daengle-user-api/src/main/java/ddog/user/presentation/review/dto/request/PostGroomingReviewInfo.java
  daengle-user-api/src/main/java/ddog/user/presentation/review/dto/response/CareReviewDetailResp.java
  daengle-user-api/src/main/java/ddog/user/presentation/review/dto/response/CareReviewSummaryResp.java
  daengle-user-api/src/main/java/ddog/user/presentation/review/dto/response/GroomingReviewDetailResp.java
  daengle-user-api/src/main/java/ddog/user/presentation/review/dto/response/GroomingReviewSummaryResp.java
  daengle-vet-api/src/main/java/ddog/vet/application/EstimateService.java
  daengle-vet-api/src/main/java/ddog/vet/application/ReviewService.java
  daengle-vet-api/src/main/java/ddog/vet/presentation/estimate/dto/EstimateInfo.java
  daengle-vet-api/src/main/java/ddog/vet/presentation/review/dto/ReviewSummaryResp.java
Labels: 💻 기능, 🛠️ 리팩토링

#147 [feat/daengle-68] 리뷰 조회 API 응답값 일정(schedule) 추가
  daengle-domain/src/main/java/ddog/domain/review/port/CareReviewPersist.java
  daengle-groomer-api/src/main/java/ddog/groomer/application/ReviewService.java
  daengle-groomer-api/src/main/java/ddog/groomer/application/exception/GroomingReviewException.java
  daengle-groomer-api/src/main/java/ddog/groomer/application/exception/GroomingReviewExceptionType.java
  daengle-groomer-api/src/main/java/ddog/groomer/presentation/review/dto/ReviewSummaryResp.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/adapter/CareReviewRepository.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/jpa/repository/CareReviewJpaRepository.java
  daengle-user-api/src/main/java/ddog/user/application/CareReviewService.java
  daengle-user-api/src/main/java/ddog/user/application/GroomingReviewService.java
  daengle-user-api/src/main/java/ddog/user/application/mapper/GroomingReviewMapper.java
  daengle-user-api/src/main/java/ddog/user/presentation/review/CareReviewController.java
  daengle-user-api/src/main/java/ddog/user/presentation/review/GroomingReviewController.java
  daengle-user-api/src/main/java/ddog/user/presentation/review/dto/request/UpdateGroomingReviewInfo.java
  daengle-user-api/src/main/java/ddog/user/presentation/review/dto/response/CareReviewDetailResp.java
  daengle-user-api/src/main/java/ddog/user/presentation/review/dto/response/CareReviewSummaryResp.java
  daengle-user-api/src/main/java/ddog/user/presentation/review/dto/response/GroomingReviewDetailResp.java
  daengle-user-api/src/main/java/ddog/user/presentation/review/dto/response/GroomingReviewSummaryResp.java
  daengle-vet-api/src/main/java/ddog/vet/application/ReviewService.java
  daengle-vet-api/src/main/java/ddog/vet/application/exception/CareReviewException.java
  daengle-vet-api/src/main/java/ddog/vet/application/exception/CareReviewExceptionType.java
  daengle-vet-api/src/main/java/ddog/vet/presentation/review/dto/ReviewSummaryResp.java
Labels: 💻 기능

#149 [feat/daengle-70] 리뷰 조회 API 응답값 DATE 수정
  daengle-domain/src/main/java/ddog/domain/review/Review.java
  daengle-groomer-api/src/main/java/ddog/groomer/application/ReviewService.java
  daengle-groomer-api/src/main/java/ddog/groomer/presentation/review/dto/ReviewSummaryResp.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/jpa/entity/CareReviewJpaEntity.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/jpa/entity/GroomingReviewJpaEntity.java
  daengle-user-api/src/main/java/ddog/user/application/CareReviewService.java
  daengle-user-api/src/main/java/ddog/user/application/GroomingReviewService.java
  daengle-user-api/src/main/java/ddog/user/application/mapper/CareReviewMapper.java
  daengle-user-api/src/main/java/ddog/user/application/mapper/GroomingReviewMapper.java
  daengle-user-api/src/main/java/ddog/user/presentation/review/dto/response/CareReviewSummaryResp.java
  daengle-user-api/src/main/java/ddog/user/presentation/review/dto/response/GroomingReviewSummaryResp.java
  daengle-vet-api/src/main/java/ddog/vet/application/ReviewService.java
  daengle-vet-api/src/main/java/ddog/vet/presentation/review/dto/ReviewSummaryResp.java
Labels: 🚨 핫픽스

#156 [feat/daengle-73] 상세 정보 조회 API 구현
  daengle-domain/src/main/java/ddog/domain/estimate/port/CareEstimatePersist.java
  daengle-domain/src/main/java/ddog/domain/estimate/port/GroomingEstimatePersist.java
  daengle-domain/src/main/java/ddog/domain/groomer/GroomerSummaryInfo.java
  daengle-domain/src/main/java/ddog/domain/groomer/port/GroomerPersist.java
  daengle-domain/src/main/java/ddog/domain/payment/Reservation.java
  daengle-domain/src/main/java/ddog/domain/payment/port/ReservationPersist.java
  daengle-domain/src/main/java/ddog/domain/shop/BeautyShop.java
  daengle-domain/src/main/java/ddog/domain/shop/port/BeautyShopPersist.java
  daengle-domain/src/main/java/ddog/domain/vet/port/VetPersist.java
  daengle-groomer-api/src/main/java/ddog/groomer/application/ScheduleInfoService.java
  daengle-groomer-api/src/main/java/ddog/groomer/presentation/schedule/ScheduleController.java
  daengle-groomer-api/src/main/java/ddog/groomer/presentation/schedule/dto/ScheduleResp.java
  daengle-payment-api/src/main/java/ddog/payment/presentation/dto/PostOrderInfo.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/adapter/BeautyShopRepository.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/adapter/CareEstimateRepository.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/adapter/GroomerRepository.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/adapter/GroomingEstimateRepository.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/adapter/ReservationRepository.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/adapter/VetRepository.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/jpa/entity/BeautyShopJpaEntity.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/jpa/entity/ReservationJpaEntity.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/jpa/repository/BeautyShopJpaRepository.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/jpa/repository/CareEstimateJpaRepository.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/jpa/repository/GroomerJpaRepository.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/jpa/repository/GroomingEstimateJpaRepository.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/jpa/repository/ReservationJpaRepository.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/jpa/repository/VetJpaRepository.java
  daengle-user-api/src/main/java/ddog/user/application/DetailInfoService.java
  daengle-user-api/src/main/java/ddog/user/application/exception/info/BeautyShopException.java
  daengle-user-api/src/main/java/ddog/user/application/exception/info/BeautyShopExceptionType.java
  daengle-user-api/src/main/java/ddog/user/application/mapper/ShopMapper.java
  daengle-user-api/src/main/java/ddog/user/presentation/shop/DetailInfoController.java
  daengle-user-api/src/main/java/ddog/user/presentation/shop/dto/DetailResp.java
  daengle-vet-api/src/main/java/ddog/vet/application/ScheduleInfoService.java
  daengle-vet-api/src/main/java/ddog/vet/presentation/schedule/ScheduleController.java
  daengle-vet-api/src/main/java/ddog/vet/presentation/schedule/dto/ScheduleResp.java
Labels: 💻 기능

#162 [feat/daengle-72] 결제 시스템 v2 모듈 설계
  .github/workflows/dev-integration.yml
  build.gradle
  daengle-auth/build.gradle
  daengle-chat-api/build.gradle
  daengle-groomer-api/build.gradle
  daengle-notification/build.gradle
  daengle-payment-api/build.gradle
  daengle-payment-api/src/main/java/ddog/payment/application/PaymentService.java
  daengle-payment-service/build.gradle.kts
  daengle-payment-service/src/main/kotlin/ddog/PaymentServiceApplication.kt
  daengle-payment-service/src/main/kotlin/ddog/common/WebAdapter.kt
  daengle-payment-service/src/main/kotlin/ddog/payment/adapter/in/web/api/TossPaymentController.kt
  daengle-payment-service/src/main/kotlin/ddog/payment/adapter/in/web/request/TossPaymentConfirmRequest.kt
  daengle-payment-service/src/main/kotlin/ddog/payment/adapter/in/web/response/ApiResponse.kt
  daengle-payment-service/src/main/kotlin/ddog/payment/adapter/in/web/view/CheckoutController.kt
  daengle-payment-service/src/main/kotlin/ddog/payment/adapter/in/web/view/PaymentController.kt
  daengle-payment-service/src/main/kotlin/ddog/payment/adapter/out/web/toss/config/TossPaymentConfiguration.kt
  daengle-payment-service/src/main/kotlin/ddog/payment/adapter/out/web/toss/config/TossWebClientConfiguration.kt
  daengle-payment-service/src/main/kotlin/ddog/payment/adapter/out/web/toss/executor/TossPaymentExecutor.kt
  daengle-payment-service/src/main/resources/application.yaml
  daengle-payment-service/src/main/resources/static/style.css
  daengle-payment-service/src/main/resources/templates/checkout.html
  daengle-payment-service/src/main/resources/templates/fail.html
  daengle-payment-service/src/main/resources/templates/success.html
  daengle-persistence-dynamodb/build.gradle
  daengle-persistence-dynamodb/src/main/java/ddog/persistence/dynamodb/adapter/ChatMessageDynamoRepository.java
  daengle-persistence-mysql/build.gradle
  daengle-user-api/build.gradle
  daengle-vet-api/build.gradle
  settings.gradle
Labels: 💻 기능

#159 [fix/daengle-75] 메서드명 및 변수명 변경
  daengle-groomer-api/src/main/java/ddog/groomer/application/ScheduleInfoService.java
  daengle-user-api/src/main/java/ddog/user/application/DetailInfoService.java
  daengle-vet-api/src/main/java/ddog/vet/application/ScheduleInfoService.java
Labels: 🚨 핫픽스

#153 [feat/daengle-71] 사용자 예약 견적서 페이징 조회 및 견적서 상세 조회 API 구현
  daengle-domain/src/main/java/ddog/domain/payment/Order.java
  daengle-domain/src/main/java/ddog/domain/payment/Reservation.java
  daengle-domain/src/main/java/ddog/domain/payment/port/ReservationPersist.java
  daengle-payment-api/src/main/java/ddog/payment/application/mapper/OrderMapper.java
  daengle-payment-api/src/main/java/ddog/payment/application/mapper/ReservationMapper.java
  daengle-payment-api/src/main/java/ddog/payment/presentation/dto/PostOrderInfo.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/adapter/ReservationRepository.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/jpa/entity/OrderJpaEntity.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/jpa/entity/ReservationJpaEntity.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/jpa/repository/ReservationJpaRepository.java
  daengle-user-api/src/main/java/ddog/user/application/AccountService.java
  daengle-user-api/src/main/java/ddog/user/application/ReservationService.java
  daengle-user-api/src/main/java/ddog/user/application/mapper/ReservationMapper.java
  daengle-user-api/src/main/java/ddog/user/presentation/reservation/ReservationController.java
  daengle-user-api/src/main/java/ddog/user/presentation/reservation/dto/EstimateDetail.java
  daengle-user-api/src/main/java/ddog/user/presentation/reservation/dto/ReservationInfo.java
Labels: 💻 기능

#165 [fix/daengle-78] 미용샵 이미지 리스트 -> 개별 이미지 변경
  daengle-domain/src/main/java/ddog/domain/shop/BeautyShop.java
  daengle-domain/src/main/java/ddog/domain/shop/port/BeautyShopPersist.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/adapter/BeautyShopRepository.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/jpa/entity/BeautyShopJpaEntity.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/jpa/repository/BeautyShopJpaRepository.java
  daengle-user-api/src/main/java/ddog/user/application/DetailInfoService.java
  daengle-user-api/src/main/java/ddog/user/application/mapper/ShopMapper.java
  daengle-user-api/src/main/java/ddog/user/presentation/shop/dto/DetailResp.java
Labels: 😢 이슈

#164 [feat/daengle-76] 프로필 조회 및 수정 관련 API 기능 추가
  daengle-domain/src/main/java/ddog/domain/groomer/Groomer.java
  daengle-domain/src/main/java/ddog/domain/groomer/License.java
  daengle-domain/src/main/java/ddog/domain/groomer/port/LicensePersist.java
  daengle-domain/src/main/java/ddog/domain/vet/Vet.java
  daengle-groomer-api/src/main/java/ddog/groomer/application/AccountService.java
  daengle-groomer-api/src/main/java/ddog/groomer/application/mapper/GroomerMapper.java
  daengle-groomer-api/src/main/java/ddog/groomer/presentation/account/dto/ProfileInfo.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/adapter/LicenseRepository.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/jpa/entity/GroomerJpaEntity.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/jpa/entity/LicenseJpaEntity.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/jpa/entity/VetJpaEntity.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/jpa/repository/LicenseJpaRepository.java
  daengle-vet-api/src/main/java/ddog/vet/application/AccountService.java
  daengle-vet-api/src/main/java/ddog/vet/application/mapper/VetMapper.java
  daengle-vet-api/src/main/java/ddog/vet/presentation/account/AccountController.java
  daengle-vet-api/src/main/java/ddog/vet/presentation/account/dto/ProfileInfo.java
  daengle-vet-api/src/main/java/ddog/vet/presentation/account/dto/UpdateInfo.java
Labels: 💻 기능

#167 [feat/daengle-79] 회원/비회원 검증 API 및 미용사 instagram ID 를 받을 수 있는 필드 추가
  daengle-auth/src/main/java/ddog/auth/resolver/PayloadArgumentResolver.java
  daengle-domain/src/main/java/ddog/domain/groomer/Groomer.java
  daengle-groomer-api/src/main/java/ddog/groomer/application/AccountService.java
  daengle-groomer-api/src/main/java/ddog/groomer/application/mapper/GroomerMapper.java
  daengle-groomer-api/src/main/java/ddog/groomer/presentation/account/dto/ProfileInfo.java
  daengle-groomer-api/src/main/java/ddog/groomer/presentation/account/dto/UpdateInfoReq.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/jpa/entity/GroomerJpaEntity.java
  daengle-user-api/src/main/java/ddog/user/application/auth/AuthService.java
  daengle-user-api/src/main/java/ddog/user/presentation/auth/AuthController.java
  daengle-user-api/src/main/java/ddog/user/presentation/auth/dto/ValidateResp.java
  daengle-user-api/src/test/java/ReviewBanWordFilteringPerformanceTest.java
  daengle-user-api/src/test/java/ReviewBanWordFilteringTest.java
  daengle-vet-api/src/main/java/ddog/vet/application/EstimateService.java
Labels: 💻 기능

#174 [fix/daengle-82] 리뷰 조회 API 응답값 수정 + 리뷰 작성 요청 관련 유효성 검사 로직 추가
  daengle-domain/src/main/java/ddog/domain/review/port/CareReviewPersist.java
  daengle-domain/src/main/java/ddog/domain/review/port/GroomingReviewPersist.java
  daengle-payment-api/src/main/java/ddog/payment/application/PaymentService.java
  daengle-payment-api/src/main/java/ddog/payment/application/dto/response/PaymentHistoryDetail.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/adapter/CareReviewRepository.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/adapter/GroomingReviewRepository.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/jpa/repository/CareReviewJpaRepository.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/jpa/repository/GroomingReviewJpaRepository.java
  daengle-user-api/src/main/java/ddog/user/application/CareReviewService.java
  daengle-user-api/src/main/java/ddog/user/application/GroomingReviewService.java
  daengle-user-api/src/main/java/ddog/user/application/exception/ReviewExceptionType.java
  daengle-user-api/src/main/java/ddog/user/presentation/review/dto/response/CareReviewDetailResp.java
  daengle-user-api/src/main/java/ddog/user/presentation/review/dto/response/GroomingReviewDetailResp.java
Labels: 🚨 핫픽스

#177 [fix/daengle-85] 리뷰 수, 예약 수, 전체 스케줄 수 등 타입 변경
  daengle-groomer-api/src/main/java/ddog/groomer/application/ScheduleInfoService.java
  daengle-groomer-api/src/main/java/ddog/groomer/presentation/schedule/dto/ScheduleResp.java
  daengle-vet-api/src/main/java/ddog/vet/application/ScheduleInfoService.java
  daengle-vet-api/src/main/java/ddog/vet/presentation/schedule/dto/ScheduleResp.java
Labels: 🐞 버그, 🚨 핫픽스

#179 [feat/daengle-83] 미용사/병원 마이페이지 정보 요청 API 구현
  daengle-domain/src/main/java/ddog/domain/vet/Vet.java
  daengle-groomer-api/src/main/java/ddog/groomer/application/AccountService.java
  daengle-groomer-api/src/main/java/ddog/groomer/application/mapper/GroomerMapper.java
  daengle-groomer-api/src/main/java/ddog/groomer/presentation/account/AccountController.java
  daengle-groomer-api/src/main/java/ddog/groomer/presentation/account/dto/ProfileInfo.java
  daengle-user-api/src/main/java/ddog/user/application/mapper/GroomingEstimateMapper.java
  daengle-user-api/src/main/java/ddog/user/application/mapper/ReservationMapper.java
  daengle-user-api/src/main/java/ddog/user/presentation/estimate/dto/GroomingEstimateDetail.java
  daengle-user-api/src/main/java/ddog/user/presentation/reservation/dto/EstimateDetail.java
  daengle-vet-api/src/main/java/ddog/vet/application/AccountService.java
  daengle-vet-api/src/main/java/ddog/vet/application/mapper/VetMapper.java
  daengle-vet-api/src/main/java/ddog/vet/presentation/account/AccountController.java
  daengle-vet-api/src/main/java/ddog/vet/presentation/account/dto/ProfileInfo.java
  daengle-vet-api/src/main/java/ddog/vet/presentation/account/dto/UpdateInfo.java
Labels: 💻 기능

#178 [feat/daengle-84] 사용자 마이페이지 조회 API 구현
  daengle-domain/src/main/java/ddog/domain/estimate/port/CareEstimatePersist.java
  daengle-domain/src/main/java/ddog/domain/estimate/port/GroomingEstimatePersist.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/adapter/CareEstimateRepository.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/adapter/GroomingEstimateRepository.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/jpa/repository/BeautyShopJpaRepository.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/jpa/repository/CareEstimateJpaRepository.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/jpa/repository/GroomingEstimateJpaRepository.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/jpa/repository/VetJpaRepository.java
  daengle-user-api/src/main/java/ddog/user/application/AccountInfoService.java
  daengle-user-api/src/main/java/ddog/user/application/DetailInfoService.java
  daengle-user-api/src/main/java/ddog/user/presentation/account/AccountInfoController.java
  daengle-user-api/src/main/java/ddog/user/presentation/account/dto/MyProfileResp.java
  daengle-user-api/src/main/java/ddog/user/presentation/detailInfo/DetailInfoController.java
Labels: 💻 기능

#181 [feat/daengle-86] 미용사/병원 회원/비회원 검증 API 추가 및 CORS 허용 URI 추가
  daengle-auth/src/main/java/ddog/auth/config/SecurityConfig.java
  daengle-groomer-api/src/main/java/ddog/groomer/application/auth/AuthService.java
  daengle-groomer-api/src/main/java/ddog/groomer/presentation/auth/AuthController.java
  daengle-groomer-api/src/main/java/ddog/groomer/presentation/auth/dto/ValidateResp.java
  daengle-user-api/src/main/java/ddog/user/application/auth/AuthService.java
  daengle-user-api/src/main/java/ddog/user/presentation/auth/AuthController.java
  daengle-vet-api/src/main/java/ddog/vet/application/auth/AuthService.java
  daengle-vet-api/src/main/java/ddog/vet/presentation/auth/AuthController.java
  daengle-vet-api/src/main/java/ddog/vet/presentation/auth/dto/ValidateResp.java
Labels: 💻 기능

#186 [feat/daengle-87] 리뷰 신고 관련 API 구현
  daengle-domain/src/main/java/ddog/domain/review/ReportedReview.java
  daengle-domain/src/main/java/ddog/domain/review/enums/ReportType.java
  daengle-domain/src/main/java/ddog/domain/review/port/GroomingReviewPersist.java
  daengle-domain/src/main/java/ddog/domain/review/port/ReportedReviewPersist.java
  daengle-groomer-api/src/main/java/ddog/groomer/Test.java
  daengle-groomer-api/src/main/java/ddog/groomer/application/ReviewService.java
  daengle-groomer-api/src/main/java/ddog/groomer/application/exception/GroomingReviewExceptionType.java
  daengle-groomer-api/src/main/java/ddog/groomer/application/mapper/ReportReviewMapper.java
  daengle-groomer-api/src/main/java/ddog/groomer/presentation/review/ReviewController.java
  daengle-groomer-api/src/main/java/ddog/groomer/presentation/review/dto/ReportReviewReq.java
  daengle-groomer-api/src/main/java/ddog/groomer/presentation/review/dto/ReportReviewResp.java
  daengle-groomer-api/src/main/java/ddog/groomer/presentation/review/dto/ReportedReviewListResp.java
  daengle-groomer-api/src/main/java/ddog/groomer/presentation/review/dto/ReportedReviewSummaryResp.java
  daengle-groomer-api/src/main/java/ddog/groomer/presentation/review/dto/SubmitReportReviewResp.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/adapter/GroomingReviewRepository.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/adapter/ReportedReviewRepository.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/jpa/entity/ReportedReviewJpaEntity.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/jpa/repository/GroomingReviewJpaRepository.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/jpa/repository/ReportedReviewJpaRepository.java
  daengle-vet-api/src/main/java/ddog/vet/application/ReviewService.java
  daengle-vet-api/src/main/java/ddog/vet/application/mapper/ReportReviewMapper.java
  daengle-vet-api/src/main/java/ddog/vet/presentation/review/ReviewController.java
  daengle-vet-api/src/main/java/ddog/vet/presentation/review/dto/ReportReviewReq.java
  daengle-vet-api/src/main/java/ddog/vet/presentation/review/dto/ReportReviewResp.java
  daengle-vet-api/src/main/java/ddog/vet/presentation/review/dto/ReportedReviewListResp.java
  daengle-vet-api/src/main/java/ddog/vet/presentation/review/dto/ReportedReviewSummaryResp.java
  daengle-vet-api/src/main/java/ddog/vet/presentation/review/dto/SubmitReportReviewResp.java
Labels: 💻 기능

#188 [fix/daengle-90] 결제 요청, API 스펙 변경
  daengle-groomer-api/src/main/java/ddog/groomer/application/ReviewService.java
  daengle-payment-api/src/main/java/ddog/payment/application/OrderService.java
  daengle-payment-api/src/main/java/ddog/payment/application/exception/OrderExceptionType.java
  daengle-payment-api/src/main/java/ddog/payment/application/mapper/OrderMapper.java
  daengle-payment-api/src/main/java/ddog/payment/presentation/dto/PostOrderInfo.java
  daengle-vet-api/src/main/java/ddog/vet/application/ReviewService.java
Labels: 🚨 핫픽스

#185 [feat/daengle-46] 채팅 관련 API 구현
  .github/workflows/dev-deploy.yml
  .github/workflows/dev-integration.yml
  .github/workflows/prod-deploy.yml
  .github/workflows/prod-integration.yml
  daengle-auth/src/main/java/ddog/auth/config/SecurityConfig.java
  daengle-chat-api/src/main/java/ddog/chat/application/ChatService.java
  daengle-chat-api/src/main/java/ddog/chat/application/config/WebSocketConfig.java
  daengle-chat-api/src/main/java/ddog/chat/presentation/ChatController.java
  daengle-chat-api/src/main/java/ddog/chat/presentation/DeployCheckController.java
  daengle-chat-api/src/main/java/ddog/chat/presentation/dto/ChatMessageReq.java
  daengle-chat-api/src/main/java/ddog/chat/presentation/dto/ChatMessagesListResp.java
  daengle-chat-api/src/main/java/ddog/chat/presentation/dto/PartnerChatRoomListResp.java
  daengle-chat-api/src/main/java/ddog/chat/presentation/dto/UserChatRoomListResp.java
  daengle-domain/src/main/java/ddog/domain/chat/ChatMessage.java
  daengle-domain/src/main/java/ddog/domain/chat/ChatRoom.java
  daengle-domain/src/main/java/ddog/domain/chat/enums/PartnerType.java
  daengle-domain/src/main/java/ddog/domain/chat/port/ChatMessagePersist.java
  daengle-domain/src/main/java/ddog/domain/chat/port/ChatRoomPersist.java
  daengle-domain/src/main/java/ddog/domain/estimate/port/CareEstimatePersist.java
  daengle-domain/src/main/java/ddog/domain/estimate/port/GroomingEstimatePersist.java
  daengle-persistence-dynamodb/src/main/java/ddog/persistence/dynamodb/adapter/ChatMessageDynamoRepository.java
  daengle-persistence-dynamodb/src/main/java/ddog/persistence/dynamodb/entity/ChatMessageDynamoEntity.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/adapter/CareEstimateRepository.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/adapter/ChatRoomRepository.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/adapter/GroomingEstimateRepository.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/jpa/entity/ChatRoomJpaEntity.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/jpa/repository/CareEstimateJpaRepository.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/jpa/repository/ChatRoomJpaRepository.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/jpa/repository/GroomingEstimateJpaRepository.java
  daengle-user-api/src/main/java/ddog/user/application/DetailInfoService.java
  daengle-user-api/src/main/java/ddog/user/presentation/detailInfo/DetailInfoController.java
Labels: 💻 기능

#194 [fix/daengle-94] CORS 허용 URI 추가
  daengle-auth/src/main/java/ddog/auth/config/SecurityConfig.java
Labels: 🚨 핫픽스

#191 [fix/daengle-92] 채팅 대화내역 반환 형식 변경
  daengle-auth/src/main/java/ddog/auth/config/SecurityConfig.java
  daengle-chat-api/src/main/java/ddog/chat/application/ChatService.java
  daengle-chat-api/src/main/java/ddog/chat/application/config/WebSocketConfig.java
  daengle-chat-api/src/main/java/ddog/chat/presentation/ChatController.java
  daengle-chat-api/src/main/java/ddog/chat/presentation/dto/ChatMessagesListResp.java
Labels: 💻 기능, 😢 이슈

#196 [fix/daengle-95] 인스타 아이디 필드 추가
  daengle-user-api/src/main/java/ddog/user/application/DetailInfoService.java
  daengle-user-api/src/main/java/ddog/user/presentation/detailInfo/dto/DetailResp.java
Labels: 🚨 핫픽스

#201 [feat/daengle-91] 댕글미터 도메인 설계, 댕글미터 비즈니스 로직 구현
  daengle-domain/src/main/java/ddog/domain/groomer/Groomer.java
  daengle-domain/src/main/java/ddog/domain/groomer/GroomerDaengleMeter.java
  daengle-domain/src/main/java/ddog/domain/groomer/port/GroomerDaengleMeterPersist.java
  daengle-domain/src/main/java/ddog/domain/groomer/port/GroomerPersist.java
  daengle-domain/src/main/java/ddog/domain/payment/Reservation.java
  daengle-domain/src/main/java/ddog/domain/review/Review.java
  daengle-domain/src/main/java/ddog/domain/vet/Vet.java
  daengle-domain/src/main/java/ddog/domain/vet/VetDaengleMeter.java
  daengle-domain/src/main/java/ddog/domain/vet/port/VetDaengleMeterPersist.java
  daengle-domain/src/main/java/ddog/domain/vet/port/VetPersist.java
  daengle-groomer-api/src/main/java/ddog/groomer/application/AccountService.java
  daengle-groomer-api/src/main/java/ddog/groomer/application/mapper/GroomerDaengleMeterMapper.java
  daengle-groomer-api/src/main/java/ddog/groomer/application/mapper/GroomerMapper.java
  daengle-payment-api/src/main/java/ddog/payment/presentation/dto/PostOrderInfo.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/adapter/GroomerDaengleMeterRepository.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/adapter/GroomerRepository.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/adapter/VetDaengleMeterRepository.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/adapter/VetRepository.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/jpa/entity/CareReviewJpaEntity.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/jpa/entity/GroomerDanegleMeterJpaEntity.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/jpa/entity/GroomingReviewJpaEntity.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/jpa/entity/VetDaengleMeterJpaEntity.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/jpa/repository/GroomerDaengleMeterJpaRepository.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/jpa/repository/VetDaengleMeterJpaRepository.java
  daengle-user-api/src/main/java/ddog/user/application/CareReviewService.java
  daengle-user-api/src/main/java/ddog/user/application/GroomingReviewService.java
  daengle-user-api/src/main/java/ddog/user/application/exception/account/GroomerExceptionType.java
  daengle-user-api/src/main/java/ddog/user/application/exception/account/VetExceptionType.java
  daengle-user-api/src/main/java/ddog/user/presentation/review/dto/request/PostCareReviewInfo.java
  daengle-user-api/src/main/java/ddog/user/presentation/review/dto/request/PostGroomingReviewInfo.java
  daengle-user-api/src/main/java/ddog/user/presentation/review/dto/request/UpdateCareReviewInfo.java
  daengle-user-api/src/main/java/ddog/user/presentation/review/dto/request/UpdateGroomingReviewInfo.java
  daengle-vet-api/src/main/java/ddog/vet/application/AccountService.java
  daengle-vet-api/src/main/java/ddog/vet/application/mapper/VetDaengleMeterMapper.java
  daengle-vet-api/src/main/java/ddog/vet/application/mapper/VetMapper.java
Labels: 💻 기능

#197 [feat/daengle-93] 미용샵 페이지 수정 및 조회 API 구현
  daengle-domain/src/main/java/ddog/domain/shop/BeautyShop.java
  daengle-domain/src/main/java/ddog/domain/shop/port/BeautyShopPersist.java
  daengle-domain/src/main/java/ddog/domain/vet/Vet.java
  daengle-groomer-api/src/main/java/ddog/groomer/application/AccountService.java
  daengle-groomer-api/src/main/java/ddog/groomer/application/mapper/BeautyShopMapper.java
  daengle-groomer-api/src/main/java/ddog/groomer/presentation/account/AccountController.java
  daengle-groomer-api/src/main/java/ddog/groomer/presentation/account/dto/ShopInfo.java
  daengle-groomer-api/src/main/java/ddog/groomer/presentation/account/dto/UpdateShopReq.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/jpa/entity/BeautyShopJpaEntity.java
  daengle-vet-api/src/main/java/ddog/vet/application/AccountService.java
Labels: 💻 기능

#202 [fix/daengle-98] 채팅 시간 타입 변경
  daengle-chat-api/src/main/java/ddog/chat/application/ChatService.java
  daengle-chat-api/src/main/java/ddog/chat/presentation/dto/ChatMessagesListResp.java
Labels: 🚨 핫픽스

#207 [fix/daengle-99] 상세정보 필드명 수정 및 데이터 추가
  daengle-user-api/src/main/java/ddog/user/application/DetailInfoService.java
  daengle-user-api/src/main/java/ddog/user/presentation/detailInfo/dto/DetailResp.java
Labels: 🚨 핫픽스, 😢 이슈

#208 [feat/daengle-81] 결제 시스템, 예약금 전체/부분 환불 기능 구현
  .github/workflows/dev-integration.yml
  daengle-domain/src/main/java/ddog/domain/payment/Payment.java
  daengle-domain/src/main/java/ddog/domain/payment/port/PaymentPersist.java
  daengle-domain/src/main/java/ddog/domain/payment/port/ReservationPersist.java
  daengle-payment-api/src/main/java/ddog/payment/application/PaymentService.java
  daengle-payment-api/src/main/java/ddog/payment/application/dto/request/CancelPaymentsRequest.java
  daengle-payment-api/src/main/java/ddog/payment/application/dto/response/PaymentCancelResp.java
  daengle-payment-api/src/main/java/ddog/payment/application/exception/PaymentExceptionType.java
  daengle-payment-api/src/main/java/ddog/payment/presentation/PaymentController.java
  daengle-payment-service/build.gradle.kts
  daengle-payment-service/src/main/kotlin/ddog/PaymentServiceApplication.kt
  daengle-payment-service/src/main/kotlin/ddog/common/WebAdapter.kt
  daengle-payment-service/src/main/kotlin/ddog/payment/adapter/in/web/api/TossPaymentController.kt
  daengle-payment-service/src/main/kotlin/ddog/payment/adapter/in/web/request/TossPaymentConfirmRequest.kt
  daengle-payment-service/src/main/kotlin/ddog/payment/adapter/in/web/response/ApiResponse.kt
  daengle-payment-service/src/main/kotlin/ddog/payment/adapter/in/web/view/CheckoutController.kt
  daengle-payment-service/src/main/kotlin/ddog/payment/adapter/in/web/view/PaymentController.kt
  daengle-payment-service/src/main/kotlin/ddog/payment/adapter/out/web/toss/config/TossPaymentConfiguration.kt
  daengle-payment-service/src/main/kotlin/ddog/payment/adapter/out/web/toss/config/TossWebClientConfiguration.kt
  daengle-payment-service/src/main/kotlin/ddog/payment/adapter/out/web/toss/executor/TossPaymentExecutor.kt
  daengle-payment-service/src/main/resources/application.yaml
  daengle-payment-service/src/main/resources/static/style.css
  daengle-payment-service/src/main/resources/templates/checkout.html
  daengle-payment-service/src/main/resources/templates/fail.html
  daengle-payment-service/src/main/resources/templates/success.html
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/adapter/PaymentRepository.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/adapter/ReservationRepository.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/jpa/repository/PaymentJpaRepository.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/jpa/repository/ReservationJpaRepository.java
  daengle-user-api/src/main/java/ddog/user/application/ReservationService.java
  daengle-user-api/src/main/java/ddog/user/application/mapper/ReservationMapper.java
  daengle-user-api/src/main/java/ddog/user/presentation/reservation/dto/EstimateDetail.java
  daengle-user-api/src/main/java/ddog/user/presentation/reservation/dto/ReservationInfo.java
  settings.gradle
Labels: 💻 기능

#206 [fix/daengle-101] 채팅 관련 데이터 및 api 수정
  daengle-chat-api/src/main/java/ddog/chat/application/ChatService.java
  daengle-chat-api/src/main/java/ddog/chat/presentation/ChatController.java
  daengle-chat-api/src/main/java/ddog/chat/presentation/dto/ChatMessagesListResp.java
  daengle-chat-api/src/main/java/ddog/chat/presentation/dto/PartnerChatRoomListResp.java
  daengle-chat-api/src/main/java/ddog/chat/presentation/dto/UserChatRoomListResp.java
Labels: 🐞 버그, 😢 이슈

#210 [feat/daengle-102] 미용샵 프로필 수정 페이지 정보 조회 API 보완
  daengle-groomer-api/src/main/java/ddog/groomer/application/AccountService.java
  daengle-groomer-api/src/main/java/ddog/groomer/application/mapper/BeautyShopMapper.java
  daengle-groomer-api/src/main/java/ddog/groomer/presentation/account/AccountController.java
  daengle-groomer-api/src/main/java/ddog/groomer/presentation/account/dto/ShopInfo.java
Labels: 💻 기능

#212 [feat/daengle-103] 채팅 api 추가
  daengle-chat-api/src/main/java/ddog/chat/application/ChatService.java
  daengle-chat-api/src/main/java/ddog/chat/presentation/ChatController.java
Labels: 💻 기능

#213 [feat/daengle-💯] 결제 시스템, 멱등성 보장 설계 및 구현
  daengle-domain/src/main/java/ddog/domain/payment/Order.java
  daengle-domain/src/main/java/ddog/domain/payment/port/OrderPersist.java
  daengle-payment-api/src/main/java/ddog/payment/application/OrderService.java
  daengle-payment-api/src/main/java/ddog/payment/application/PaymentService.java
  daengle-payment-api/src/main/java/ddog/payment/application/exception/OrderExceptionType.java
  daengle-payment-api/src/main/java/ddog/payment/application/exception/PaymentExceptionType.java
  daengle-payment-api/src/main/java/ddog/payment/application/mapper/OrderMapper.java
  daengle-payment-api/src/main/java/ddog/payment/presentation/OrderController.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/adapter/OrderRepository.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/jpa/entity/OrderJpaEntity.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/jpa/repository/OrderJpaRepository.java
Labels: 💻 기능, ‼️ 주목

#216 [fix/daengle-104] 채팅 데이터 견적서 제외
  daengle-chat-api/src/main/java/ddog/chat/application/ChatService.java
  daengle-chat-api/src/main/java/ddog/chat/presentation/dto/ChatMessagesListResp.java
  daengle-domain/src/main/java/ddog/domain/estimate/port/GroomingEstimatePersist.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/adapter/GroomingEstimateRepository.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/jpa/repository/GroomingEstimateJpaRepository.java
Labels: 🚨 핫픽스

#218 [fix/daengle-106] 예약 견적서 상세 조회 데이터 조회중 조회 로직 수정
  daengle-user-api/src/main/java/ddog/user/application/ReservationService.java
Labels: 🐞 버그, 🚨 핫픽스

#220 [fix/daengle-97] 메인 API 필드 수정 및 사용자 주소 전달
  daengle-user-api/src/main/java/ddog/user/application/DetailInfoService.java
  daengle-user-api/src/main/java/ddog/user/application/mapper/DetailInfoMapper.java
  daengle-user-api/src/main/java/ddog/user/presentation/detailInfo/dto/DetailResp.java
Labels: 🚨 핫픽스

#221 [feat/daengle-105] 금칙어 필터링 시스템 v3 구현
  daengle-domain/src/main/java/ddog/domain/filtering/AhoCorasickMatcher.java
  daengle-domain/src/main/java/ddog/domain/filtering/BanWordValidator.java
  daengle-domain/src/main/java/ddog/domain/filtering/ContentNormalizer.java
  daengle-domain/src/main/java/ddog/domain/filtering/KMPMatcher.java
  daengle-domain/src/main/java/ddog/domain/filtering/TrieNode.java
  daengle-domain/src/test/java/ReviewBanWordFilteringAccuracyTest.java
  daengle-domain/src/test/java/ReviewBanWordFilteringPerformanceTest.java
  daengle-user-api/src/main/java/ddog/user/application/CareReviewService.java
  daengle-user-api/src/main/java/ddog/user/application/GroomingReviewService.java
Labels: 💻 기능, ✅ 테스트

#228 [feat/daengle-110] 결제 시스템, 무결성 제약조건을 활용한 멱등성 보장
  daengle-domain/src/main/java/ddog/domain/payment/Payment.java
  daengle-domain/src/main/java/ddog/domain/payment/port/PaymentPersist.java
  daengle-payment-api/src/main/java/ddog/payment/application/OrderService.java
  daengle-payment-api/src/main/java/ddog/payment/application/PaymentService.java
  daengle-payment-api/src/main/java/ddog/payment/application/exception/PaymentExceptionType.java
  daengle-payment-api/src/main/java/ddog/payment/application/mapper/PaymentMapper.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/adapter/PaymentRepository.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/jpa/entity/PaymentJpaEntity.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/jpa/repository/PaymentJpaRepository.java
Labels: 💻 기능, ‼️ 주목

#230 [feat/daengle-108] 회원/파트너 계정 탈퇴 관련 정보 조회 및 탈퇴 기능 구현
  daengle-domain/src/main/java/ddog/domain/groomer/port/GroomerPersist.java
  daengle-domain/src/main/java/ddog/domain/payment/enums/ReservationStatus.java
  daengle-domain/src/main/java/ddog/domain/payment/port/PaymentPersist.java
  daengle-domain/src/main/java/ddog/domain/payment/port/ReservationPersist.java
  daengle-domain/src/main/java/ddog/domain/user/port/UserPersist.java
  daengle-domain/src/main/java/ddog/domain/vet/port/VetPersist.java
  daengle-groomer-api/src/main/java/ddog/groomer/application/AccountService.java
  daengle-groomer-api/src/main/java/ddog/groomer/presentation/account/AccountController.java
  daengle-groomer-api/src/main/java/ddog/groomer/presentation/account/dto/WithdrawInfoResp.java
  daengle-groomer-api/src/main/java/ddog/groomer/presentation/account/dto/WithdrawResp.java
  daengle-payment-api/src/main/java/ddog/payment/presentation/PaymentController.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/adapter/GroomerRepository.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/adapter/PaymentRepository.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/adapter/ReservationRepository.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/adapter/UserRepository.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/adapter/VetRepository.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/jpa/repository/GroomerJpaRepository.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/jpa/repository/PaymentJpaRepository.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/jpa/repository/ReservationJpaRepository.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/jpa/repository/UserJpaRepository.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/jpa/repository/VetJpaRepository.java
  daengle-user-api/src/main/java/ddog/user/application/AccountService.java
  daengle-user-api/src/main/java/ddog/user/presentation/account/AccountController.java
  daengle-user-api/src/main/java/ddog/user/presentation/account/dto/WithdrawInfoResp.java
  daengle-user-api/src/main/java/ddog/user/presentation/account/dto/WithdrawResp.java
  daengle-vet-api/src/main/java/ddog/vet/application/AccountService.java
  daengle-vet-api/src/main/java/ddog/vet/presentation/account/AccountController.java
  daengle-vet-api/src/main/java/ddog/vet/presentation/account/dto/WithdrawInfoResp.java
  daengle-vet-api/src/main/java/ddog/vet/presentation/account/dto/WithdrawResp.java
Labels: 💻 기능

#229 [feat/daengle-107] 미용사/병원 리뷰에 따른 뱃지 선정 및 댕글미터 가산점 로직 구현
  daengle-domain/src/main/java/ddog/domain/groomer/Groomer.java
  daengle-domain/src/main/java/ddog/domain/groomer/GroomerKeyword.java
  daengle-domain/src/main/java/ddog/domain/groomer/GroomerSummaryInfo.java
  daengle-domain/src/main/java/ddog/domain/groomer/enums/GroomingBadge.java
  daengle-domain/src/main/java/ddog/domain/groomer/enums/GroomingKeyword.java
  daengle-domain/src/main/java/ddog/domain/user/User.java
  daengle-domain/src/main/java/ddog/domain/vet/Vet.java
  daengle-domain/src/main/java/ddog/domain/vet/VetKeyword.java
  daengle-domain/src/main/java/ddog/domain/vet/enums/CareBadge.java
  daengle-domain/src/main/java/ddog/domain/vet/enums/CareKeyword.java
  daengle-groomer-api/src/main/java/ddog/groomer/application/mapper/GroomerMapper.java
  daengle-groomer-api/src/main/java/ddog/groomer/presentation/account/dto/ProfileInfo.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/jpa/entity/GroomerJpaEntity.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/jpa/entity/GroomerKeywordJpaEntity.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/jpa/entity/VetJpaEntity.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/jpa/entity/VetKeywordJpaEntity.java
  daengle-user-api/src/main/java/ddog/user/application/CareReviewService.java
  daengle-user-api/src/main/java/ddog/user/application/DetailInfoService.java
  daengle-user-api/src/main/java/ddog/user/application/EstimateService.java
  daengle-user-api/src/main/java/ddog/user/application/GroomingReviewService.java
  daengle-user-api/src/main/java/ddog/user/application/ReservationService.java
  daengle-user-api/src/main/java/ddog/user/application/mapper/CareEstimateMapper.java
  daengle-user-api/src/main/java/ddog/user/application/mapper/GroomingEstimateMapper.java
  daengle-user-api/src/main/java/ddog/user/application/mapper/ReservationMapper.java
  daengle-user-api/src/main/java/ddog/user/presentation/detailInfo/dto/DetailResp.java
  daengle-user-api/src/main/java/ddog/user/presentation/estimate/EstimateController.java
  daengle-user-api/src/main/java/ddog/user/presentation/estimate/dto/CareEstimateDetail.java
  daengle-user-api/src/main/java/ddog/user/presentation/estimate/dto/EstimateInfo.java
  daengle-user-api/src/main/java/ddog/user/presentation/estimate/dto/GroomingEstimateDetail.java
  daengle-user-api/src/main/java/ddog/user/presentation/reservation/ReservationController.java
  daengle-user-api/src/main/java/ddog/user/presentation/reservation/dto/EstimateDetail.java
  daengle-vet-api/src/main/java/ddog/vet/application/mapper/VetMapper.java
  daengle-vet-api/src/main/java/ddog/vet/presentation/account/dto/ProfileInfo.java
Labels: 💻 기능, 🛠️ 리팩토링

#234 [release] Chat API 서버 배포
  .github/workflows/dev-deploy-chat.yml
  .github/workflows/dev-deploy-diff.yml
  .github/workflows/dev-deploy-groomer.yml
  .github/workflows/dev-deploy-payment.yml
  .github/workflows/dev-deploy-user.yml
  .github/workflows/dev-deploy-vet.yml
  daengle-payment-api/src/main/java/ddog/payment/presentation/DeployCheckController.java
  daengle-user-api/src/main/java/ddog/user/presentation/DeployCheckController.java
  daengle-vet-api/src/main/java/ddog/vet/presentation/DeployCheckController.java
Labels: ☄️ release

#235 [release] Groomer API 서버 배포
  .github/workflows/dev-deploy-chat.yml
  .github/workflows/dev-deploy-diff.yml
  .github/workflows/dev-deploy-groomer.yml
  .github/workflows/dev-deploy-payment.yml
  .github/workflows/dev-deploy-user.yml
  .github/workflows/dev-deploy-vet.yml
  daengle-payment-api/src/main/java/ddog/payment/presentation/DeployCheckController.java
  daengle-user-api/src/main/java/ddog/user/presentation/DeployCheckController.java
  daengle-vet-api/src/main/java/ddog/vet/presentation/DeployCheckController.java
Labels: ☄️ release

#237 [release] User API 서버 배포
  .github/workflows/dev-deploy-chat.yml
  .github/workflows/dev-deploy-diff.yml
  .github/workflows/dev-deploy-groomer.yml
  .github/workflows/dev-deploy-payment.yml
  .github/workflows/dev-deploy-user.yml
  .github/workflows/dev-deploy-vet.yml
  daengle-payment-api/src/main/java/ddog/payment/presentation/DeployCheckController.java
  daengle-user-api/src/main/java/ddog/user/presentation/DeployCheckController.java
  daengle-vet-api/src/main/java/ddog/vet/presentation/DeployCheckController.java
Labels: ☄️ release

#239 [release] Payment API 서버 재배포
  .github/workflows/dev-deploy-payment.yml
Labels: 🐞 버그, ☄️ release

#241 [fix/daengle-114] 미용실 전화번호 필드 추가
  daengle-user-api/src/main/java/ddog/user/application/DetailInfoService.java
  daengle-user-api/src/main/java/ddog/user/presentation/detailInfo/dto/DetailResp.java
Labels: 🚨 핫픽스

#243 [fix/daengle-113] 데이터베이스 필드 추가로 인한 기존 API 이슈 해결 및 기타 수정
  daengle-auth/src/main/java/ddog/auth/config/jwt/JwtTokenProvider.java
  daengle-domain/src/main/java/ddog/domain/groomer/Groomer.java
  daengle-domain/src/main/java/ddog/domain/groomer/port/GroomerKeywordPersist.java
  daengle-domain/src/main/java/ddog/domain/vet/port/VetKeywordPersist.java
  daengle-groomer-api/src/main/java/ddog/groomer/application/AccountService.java
  daengle-groomer-api/src/main/java/ddog/groomer/application/exception/account/AccountExceptionType.java
  daengle-groomer-api/src/main/java/ddog/groomer/application/mapper/GroomerMapper.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/adapter/GroomerKeywordRepository.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/adapter/VetKeywordRepository.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/jpa/entity/BeautyShopJpaEntity.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/jpa/entity/CareReviewJpaEntity.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/jpa/entity/ChatRoomJpaEntity.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/jpa/entity/PaymentJpaEntity.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/jpa/repository/GroomerKeywordJpaRepository.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/jpa/repository/VetKeywordJpaRepository.java
  daengle-user-api/src/main/java/ddog/user/application/AccountService.java
  daengle-user-api/src/main/java/ddog/user/application/CareReviewService.java
  daengle-user-api/src/main/java/ddog/user/application/GroomingReviewService.java
  daengle-user-api/src/main/java/ddog/user/application/exception/account/AccountExceptionType.java
  daengle-vet-api/src/main/java/ddog/vet/application/AccountService.java
  daengle-vet-api/src/main/java/ddog/vet/application/exception/account/AccountExceptionType.java
  daengle-vet-api/src/main/java/ddog/vet/application/mapper/VetMapper.java
  daengle-vet-api/src/main/java/ddog/vet/presentation/account/AccountController.java
Labels: 🐞 버그, 🚨 핫픽스

#245 [feat/daengle-115] 사용자/미용사/병원 회원가입시 이미 존재하는 Account 데이터가 있는지 검증로직 추가
  daengle-groomer-api/src/main/java/ddog/groomer/application/AccountService.java
  daengle-user-api/src/main/java/ddog/user/application/AccountService.java
  daengle-vet-api/src/main/java/ddog/vet/application/AccountService.java
Labels: 💻 기능

#248 [feat/daengle-117] 미용사/병원 데이터 필드 추가로 인한 기존 가입 및 수정 로직 보완
  daengle-groomer-api/src/main/java/ddog/groomer/application/mapper/GroomerMapper.java
  daengle-vet-api/src/main/java/ddog/vet/application/mapper/VetMapper.java
Labels: 💻 기능, 🛠️ 리팩토링

#242 [feat/daengle-80] 검색 API 추가
  daengle-domain/src/main/java/ddog/domain/groomer/port/GroomerPersist.java
  daengle-domain/src/main/java/ddog/domain/vet/port/VetPersist.java
  daengle-groomer-api/src/main/java/ddog/groomer/application/EstimateService.java
  daengle-groomer-api/src/main/java/ddog/groomer/presentation/estimate/EstimateController.java
  daengle-groomer-api/src/main/java/ddog/groomer/presentation/estimate/dto/EstimateInfo.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/adapter/GroomerRepository.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/adapter/VetRepository.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/jpa/repository/GroomerJpaRepository.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/jpa/repository/VetJpaRepository.java
  daengle-user-api/src/main/java/ddog/user/application/EstimateService.java
  daengle-user-api/src/main/java/ddog/user/application/ReservationService.java
  daengle-user-api/src/main/java/ddog/user/application/SearchService.java
  daengle-user-api/src/main/java/ddog/user/presentation/estimate/dto/DesignationEstimateInfo.java
  daengle-user-api/src/main/java/ddog/user/presentation/reservation/dto/ReservationInfo.java
  daengle-user-api/src/main/java/ddog/user/presentation/review/CareReviewController.java
  daengle-user-api/src/main/java/ddog/user/presentation/review/GroomingReviewController.java
  daengle-user-api/src/main/java/ddog/user/presentation/search/SearchController.java
  daengle-user-api/src/main/java/ddog/user/presentation/search/dto/SearchGroomingResultByKeyword.java
  daengle-user-api/src/main/java/ddog/user/presentation/search/dto/SearchVetResultByKeyword.java
  daengle-vet-api/src/main/java/ddog/vet/application/EstimateService.java
  daengle-vet-api/src/main/java/ddog/vet/presentation/estimate/EstimateController.java
  daengle-vet-api/src/main/java/ddog/vet/presentation/estimate/dto/EstimateInfo.java
Labels: 💻 기능

#250 [feat/daengle-118] 미용사측 미용실 상세 페이지 조회 API 구현
  daengle-groomer-api/src/main/java/ddog/groomer/application/AccountService.java
  daengle-groomer-api/src/main/java/ddog/groomer/presentation/account/AccountController.java
  daengle-groomer-api/src/main/java/ddog/groomer/presentation/account/dto/ShopDetailInfo.java
Labels: 💻 기능

#253 [feat/daengle-116] 결제시스템, 타임아웃 설정
  daengle-payment-api/build.gradle
  daengle-payment-api/src/main/java/ddog/payment/application/PaymentService.java
  daengle-payment-api/src/main/java/ddog/payment/application/exception/PaymentExceptionType.java
Labels: 💻 기능, 😢 이슈

#254 [feat/daengle-119] 알림톡 관련 타임아웃 설정
  daengle-groomer-api/src/main/java/ddog/groomer/application/ScheduleInfoService.java
  daengle-notification/build.gradle
  daengle-notification/src/main/java/ddog/notification/application/KakaoNotificationService.java
Labels: 💻 기능, ✅ 테스트

#256 [feat/daengle-120] httpOnly 쿠키로 등록되어 있는 refreshToken을 받아 accessToken 생성해주는 로직 구현
  daengle-auth/src/main/java/ddog/auth/config/SecurityConfig.java
  daengle-auth/src/main/java/ddog/auth/config/jwt/JwtTokenProvider.java
  daengle-auth/src/main/java/ddog/auth/exception/AuthExceptionType.java
  daengle-groomer-api/src/main/java/ddog/groomer/application/auth/AuthService.java
  daengle-groomer-api/src/main/java/ddog/groomer/presentation/auth/AuthController.java
  daengle-user-api/src/main/java/ddog/user/application/auth/AuthService.java
  daengle-user-api/src/main/java/ddog/user/presentation/auth/AuthController.java
  daengle-vet-api/src/main/java/ddog/vet/application/auth/AuthService.java
  daengle-vet-api/src/main/java/ddog/vet/presentation/auth/AuthController.java
Labels: 💻 기능, 🛠️ 리팩토링

#259 [fix/daengle-122] 비회원 로직 수정
  daengle-groomer-api/src/main/java/ddog/groomer/presentation/account/AccountController.java
  daengle-user-api/src/main/java/ddog/user/application/DetailInfoService.java
Labels: 💻 기능

#263 [feat/daengle-89] 파트너 예약 관련 상세 정보
  daengle-domain/src/main/java/ddog/domain/estimate/Estimate.java
  daengle-domain/src/main/java/ddog/domain/estimate/GroomingEstimate.java
  daengle-domain/src/main/java/ddog/domain/estimate/port/CareEstimatePersist.java
  daengle-domain/src/main/java/ddog/domain/estimate/port/GroomingEstimatePersist.java
  daengle-groomer-api/src/main/java/ddog/groomer/application/EstimateManageService.java
  daengle-groomer-api/src/main/java/ddog/groomer/application/ScheduleInfoService.java
  daengle-groomer-api/src/main/java/ddog/groomer/presentation/estimate/EstimateMangeController.java
  daengle-groomer-api/src/main/java/ddog/groomer/presentation/estimate/dto/PetInfo.java
  daengle-groomer-api/src/main/java/ddog/groomer/presentation/estimate/dto/PetProfile.java
  daengle-groomer-api/src/main/java/ddog/groomer/presentation/estimate/dto/ReservationEstimateContent.java
  daengle-groomer-api/src/main/java/ddog/groomer/presentation/estimate/dto/WeekScheduleResp.java
  daengle-payment-api/src/main/java/ddog/payment/application/OrderService.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/adapter/CareEstimateRepository.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/adapter/GroomingEstimateRepository.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/jpa/repository/CareEstimateJpaRepository.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/jpa/repository/GroomingEstimateJpaRepository.java
  daengle-vet-api/src/main/java/ddog/vet/application/EstimateManageService.java
  daengle-vet-api/src/main/java/ddog/vet/presentation/estimate/EstimateManageController.java
  daengle-vet-api/src/main/java/ddog/vet/presentation/estimate/dto/PetInfo.java
  daengle-vet-api/src/main/java/ddog/vet/presentation/estimate/dto/ReservationEstimateContent.java
  daengle-vet-api/src/main/java/ddog/vet/presentation/estimate/dto/WeekScheduleResp.java
Labels: 💻 기능

#266 [feat/daengle-121] 결제시스템, Resilience4J를 활용한 서킷브레이커 패턴 적용
  daengle-payment-api/build.gradle
  daengle-payment-api/src/main/java/ddog/payment/application/PaymentService.java
  daengle-payment-api/src/main/java/ddog/payment/presentation/PaymentController.java
Labels: 💻 기능, 😢 이슈

#224 [fix/daengle-109] JPA 엔티티 변환 시 불필요한 SELECT 이슈
  daengle-domain/src/main/java/ddog/domain/shop/dto/UpdateShopReq.java
  daengle-domain/src/main/java/ddog/domain/shop/port/BeautyShopPersist.java
  daengle-groomer-api/src/main/java/ddog/groomer/application/AccountService.java
  daengle-groomer-api/src/main/java/ddog/groomer/application/mapper/BeautyShopMapper.java
  daengle-groomer-api/src/main/java/ddog/groomer/presentation/account/AccountController.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/adapter/BeautyShopRepository.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/jpa/repository/BeautyShopJpaRepository.java
Labels: 🐞 버그, ‼️ 주목, 😢 이슈

#265 [feat/daengle-88] SQL 튜닝을 통한 MySQL 조회 성능 최적화
  daengle-domain/src/main/java/ddog/domain/estimate/dto/PetInfos.java
  daengle-domain/src/main/java/ddog/domain/estimate/port/CareEstimatePersist.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/adapter/CareEstimateRepository.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/jpa/repository/CareEstimateJpaRepository.java
  daengle-user-api/src/main/java/ddog/user/application/EstimateService.java
  daengle-user-api/src/main/java/ddog/user/presentation/estimate/EstimateController.java
Labels: 💻 기능, 🛠️ 리팩토링, ‼️ 주목

#268 [feat/daengle-124] 모니터링을 위한 모듈별 Spring Actuator 및 Prometheus 의존성 추가
  daengle-groomer-api/build.gradle
  daengle-notification/build.gradle
  daengle-payment-api/build.gradle
  daengle-user-api/build.gradle
  daengle-vet-api/build.gradle
Labels: 💻 기능

#269 [feat/daengle-125] 파트너 예약건 확인
  daengle-domain/src/main/java/ddog/domain/estimate/port/CareEstimatePersist.java
  daengle-domain/src/main/java/ddog/domain/payment/port/ReservationPersist.java
  daengle-groomer-api/src/main/java/ddog/groomer/application/AccountService.java
  daengle-groomer-api/src/main/java/ddog/groomer/application/EstimateManageService.java
  daengle-groomer-api/src/main/java/ddog/groomer/application/EstimateService.java
  daengle-groomer-api/src/main/java/ddog/groomer/application/ScheduleInfoService.java
  daengle-groomer-api/src/main/java/ddog/groomer/presentation/estimate/dto/WeekScheduleResp.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/adapter/CareEstimateRepository.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/adapter/GroomingEstimateRepository.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/adapter/ReservationRepository.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/jpa/repository/CareEstimateJpaRepository.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/jpa/repository/GroomingEstimateJpaRepository.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/jpa/repository/ReservationJpaRepository.java
  daengle-user-api/src/main/java/ddog/user/application/DetailInfoService.java
  daengle-vet-api/src/main/java/ddog/vet/application/EstimateManageService.java
  daengle-vet-api/src/main/java/ddog/vet/application/EstimateService.java
  daengle-vet-api/src/main/java/ddog/vet/application/ScheduleInfoService.java
  daengle-vet-api/src/main/java/ddog/vet/presentation/estimate/dto/WeekScheduleResp.java
Labels: 💻 기능

#272 [fix/daengle-127] 견적 관련 카운트 쿼리 로직 수정
  daengle-domain/src/main/java/ddog/domain/estimate/port/CareEstimatePersist.java
  daengle-domain/src/main/java/ddog/domain/estimate/port/GroomingEstimatePersist.java
  daengle-groomer-api/src/main/java/ddog/groomer/presentation/estimate/EstimateController.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/adapter/CareEstimateRepository.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/adapter/GroomingEstimateRepository.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/jpa/repository/CareEstimateJpaRepository.java
  daengle-persistence-mysql/src/main/java/ddog/persistence/mysql/jpa/repository/GroomingEstimateJpaRepository.java
  daengle-user-api/src/main/java/ddog/user/application/AccountInfoService.java
  daengle-user-api/src/main/java/ddog/user/application/DetailInfoService.java
  daengle-user-api/src/main/java/ddog/user/presentation/detailInfo/dto/DetailResp.java
  daengle-user-api/src/main/java/ddog/user/presentation/review/CareReviewController.java
  daengle-user-api/src/main/java/ddog/user/presentation/review/GroomingReviewController.java
  daengle-vet-api/src/main/java/ddog/vet/presentation/estimate/EstimateController.java
Labels: 🚨 핫픽스
