Repository DDog-org/daengle-server, pull requests merged in 2025-03, with the labels that each got.

#278 [refactoring/daengle-130] 기존 검색 API 조회 성능 개선 및 JPA N+1 문제 해결
  daengle-domain/src/main/java/ddog/domain/groomer/dto/SearchGroomerResultDto.java
  daengle-domain/src/main/java/ddog/domain/groomer/port/GroomerPersist.java
  daengle-persistence-rdb/src/main/java/ddog/persistence/rdb/adapter/GroomerRepository.java
  daengle-persistence-rdb/src/main/java/ddog/persistence/rdb/jpa/repository/GroomerJpaRepository.java
  daengle-user-api/src/main/java/ddog/user/application/SearchService.java
  daengle-user-api/src/main/java/ddog/user/presentation/search/SearchController.java
  daengle-user-api/src/main/java/ddog/user/presentation/search/dto/GroomerResult.java
Labels: 🛠️ 리팩토링, ‼️ 주목, 😢 이슈

#282 [refactoring/daengle-131] Spring MVC를 활용한 JWT 토큰 인증/인가 시스템 개선
  daengle-auth/src/main/java/ddog/auth/annotation/AuthPayload.java
  daengle-auth/src/main/java/ddog/auth/config/WebConfig.java
  daengle-auth/src/main/java/ddog/auth/interceptor/JwtAuthInterceptor.java
  daengle-auth/src/main/java/ddog/auth/resolver/PayloadArgumentResolver.java
  daengle-chat-api/src/main/java/ddog/chat/presentation/ChatController.java
  daengle-groomer-api/src/main/java/ddog/groomer/presentation/account/AccountController.java
  daengle-groomer-api/src/main/java/ddog/groomer/presentation/auth/AuthController.java
  daengle-groomer-api/src/main/java/ddog/groomer/presentation/estimate/EstimateController.java
  daengle-groomer-api/src/main/java/ddog/groomer/presentation/estimate/EstimateMangeController.java
  daengle-groomer-api/src/main/java/ddog/groomer/presentation/review/ReviewController.java
  daengle-groomer-api/src/main/java/ddog/groomer/presentation/schedule/ScheduleController.java
  daengle-payment-api/src/main/java/ddog/payment/presentation/OrderController.java
  daengle-payment-api/src/main/java/ddog/payment/presentation/PaymentController.java
  daengle-user-api/src/main/java/ddog/user/presentation/account/AccountController.java
  daengle-user-api/src/main/java/ddog/user/presentation/account/AccountInfoController.java
  daengle-user-api/src/main/java/ddog/user/presentation/auth/AuthController.java
  daengle-user-api/src/main/java/ddog/user/presentation/detailInfo/DetailInfoController.java
  daengle-user-api/src/main/java/ddog/user/presentation/estimate/EstimateController.java
  daengle-user-api/src/main/java/ddog/user/presentation/reservation/ReservationController.java
  daengle-user-api/src/main/java/ddog/user/presentation/review/CareReviewController.java
  daengle-user-api/src/main/java/ddog/user/presentation/review/GroomingReviewController.java
  daengle-vet-api/src/main/java/ddog/vet/presentation/account/AccountController.java
  daengle-vet-api/src/main/java/ddog/vet/presentation/auth/AuthController.java
  daengle-vet-api/src/main/java/ddog/vet/presentation/estimate/EstimateController.java
  daengle-vet-api/src/main/java/ddog/vet/presentation/estimate/EstimateManageController.java
  daengle-vet-api/src/main/java/ddog/vet/presentation/review/ReviewController.java
  daengle-vet-api/src/main/java/ddog/vet/presentation/schedule/ScheduleController.java
Labels: 💻 기능, 🛠️ 리팩토링, ‼️ 주목

#284 [refactoring/daengle-133] Payment서비스 계층과 PG사 클라이언트 라이브러리와의 강한결합 제거
  daengle-domain/src/main/java/ddog/domain/payment/Payment.java
  daengle-domain/src/main/java/ddog/domain/payment/PaymentInfo.java
  daengle-domain/src/main/java/ddog/domain/payment/enums/PaymentStatus.java
  daengle-domain/src/main/java/ddog/domain/payment/port/PaymentGateway.java
  daengle-payment-api/src/main/java/ddog/payment/application/PaymentService.java
  daengle-payment-api/src/main/java/ddog/payment/application/adapter/web/IamportPaymentGateway.java
  daengle-payment-api/src/main/java/ddog/payment/application/exception/PaymentExceptionType.java
  daengle-payment-api/src/main/java/ddog/payment/presentation/DeployCheckController.java
Labels: 🛠️ 리팩토링, ‼️ 주목
